/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#845013",
        "on-primary": "#ffffff",
        "primary-container": "#a1682a",
        "on-primary-container": "#fffbff",
        "primary-fixed": "#ffdcbf",
        "primary-fixed-dim": "#ffb873",
        "on-primary-fixed": "#2d1600",
        "on-primary-fixed-variant": "#6a3b00",
        "secondary": "#715c00",
        "on-secondary": "#ffffff",
        "secondary-container": "#fedd72",
        "on-secondary-container": "#766000",
        "secondary-fixed": "#ffe17c",
        "secondary-fixed-dim": "#e3c45b",
        "on-secondary-fixed": "#231b00",
        "on-secondary-fixed-variant": "#564500",
        "tertiary": "#325c99",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#4d75b4",
        "on-tertiary-container": "#fefcff",
        "tertiary-fixed": "#d6e3ff",
        "tertiary-fixed-dim": "#a9c7ff",
        "on-tertiary-fixed": "#001b3d",
        "on-tertiary-fixed-variant": "#174683",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "background": "#f9f9f9",
        "on-background": "#1a1c1c",
        "surface": "#f9f9f9",
        "on-surface": "#1a1c1c",
        "surface-variant": "#e2e2e2",
        "on-surface-variant": "#514439",
        "outline": "#847467",
        "outline-variant": "#d6c3b4",
        "surface-tint": "#875216",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f0f1f1",
        "inverse-primary": "#ffb873",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f4",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1rem",
        "space-xl": "1.5rem",
        "margin": "1rem",
        "gutter": "1rem"
      },
      fontFamily: {
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "display": ["Space Grotesk", "sans-serif"],
        "sans": ["Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"]
      }
    }
  },
  plugins: [],
}
