import re
from datetime import datetime, timezone
from typing import List, Dict, Any, Optional

# EXACT 20 MEDICINES WITH AUTHENTIC TABLET/MEDICINE PHOTOGRAPHY & ALIASES
EXACT_20_MEDICINES: List[Dict[str, Any]] = [
    {
        "name": "Paracetamol 500",
        "genericName": "Paracetamol",
        "activeIngredient": "Paracetamol",
        "scientificName": "N-(4-hydroxyphenyl)acetamide",
        "category": "Pain & Fever",
        "strength": "500 mg",
        "form": "Tablet",
        "quantity": 100,
        "price": 20,
        "originalPrice": 25,
        "discount": "20% OFF",
        "stock": 100,
        "brand": "Calpol 500 / GSK",
        "aliases": ["Calpol", "Calpol 500", "Crocin 500", "Paracetamol 500", "PCM 500"],
        "searchKeywords": ["paracetamol", "calpol", "crocin", "fever", "headache", "body pain", "pain relief"],
        "manufacturer": "GSK Pharmaceuticals",
        "batchNumber": "PCM-500-01",
        "manufacturingDate": datetime(2026, 1, 1, tzinfo=timezone.utc),
        "expiryDate": datetime(2028, 1, 1, tzinfo=timezone.utc),
        "image": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80",
        "images": ["https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80"],
        "description": "Effective antipyretic and analgesic for mild-to-moderate fever and body pain.",
        "status": "In Stock",
        "uses": ["Fever Reduction", "Headache", "Body Pain"],
        "precautions": ["Do not exceed 4000 mg in 24 hours", "Keep 4-6 hours interval between doses"],
        "storageInstructions": "Store below 25°C in a dry place protected from direct sunlight.",
        "rxRequired": False,
    },
    {
        "name": "Paracetamol 650",
        "genericName": "Paracetamol",
        "activeIngredient": "Paracetamol",
        "scientificName": "N-(4-hydroxyphenyl)acetamide",
        "category": "Pain & Fever",
        "strength": "650 mg",
        "form": "Tablet",
        "quantity": 100,
        "price": 30,
        "originalPrice": 38,
        "discount": "21% OFF",
        "stock": 100,
        "brand": "Dolo 650 (Micro Labs)",
        "aliases": ["Dolo", "Dolo 650", "Crocin 650", "Calpol 650", "Paracetamol 650", "PCM 650"],
        "searchKeywords": ["dolo", "dolo 650", "paracetamol 650", "crocin 650", "high fever", "severe headache", "body ache", "pain relief"],
        "manufacturer": "Micro Labs Limited",
        "batchNumber": "PCM-650-02",
        "manufacturingDate": datetime(2026, 1, 1, tzinfo=timezone.utc),
        "expiryDate": datetime(2028, 1, 1, tzinfo=timezone.utc),
        "image": "https://images.unsplash.com/photo-1585435557343-3b092031a831?w=500&auto=format&fit=crop&q=80",
        "images": ["https://images.unsplash.com/photo-1585435557343-3b092031a831?w=500&auto=format&fit=crop&q=80"],
        "description": "High-potency antipyretic formulation for severe fever, body aches, and headaches. Widely known as Dolo 650.",
        "status": "In Stock",
        "uses": ["Fever Reduction", "Severe Headache", "Post-vaccination Fever", "Body Aches"],
        "precautions": ["Do not exceed recommended dose", "Avoid alcohol consumption"],
        "storageInstructions": "Store below 25°C in a dry place.",
        "rxRequired": False,
    },
    {
        "name": "Cetirizine 10",
        "genericName": "Cetirizine",
        "activeIngredient": "Cetirizine",
        "scientificName": "2-[2-[4-[(4-chlorophenyl)-phenylmethyl]piperazin-1-yl]ethoxy]acetic acid",
        "category": "Allergy",
        "strength": "10 mg",
        "form": "Tablet",
        "quantity": 50,
        "price": 25,
        "originalPrice": 32,
        "discount": "22% OFF",
        "stock": 50,
        "brand": "AllerShield / Zyrtec",
        "aliases": ["Cetirizine", "Zyrtec", "Cetzine", "AllerShield", "Cetirizine 10"],
        "searchKeywords": ["cetirizine", "allergy", "sneezing", "runny nose", "cold", "itching"],
        "manufacturer": "PharmaCare Laboratories",
        "batchNumber": "CTZ-10-03",
        "manufacturingDate": datetime(2026, 1, 1, tzinfo=timezone.utc),
        "expiryDate": datetime(2028, 1, 1, tzinfo=timezone.utc),
        "image": "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=500&auto=format&fit=crop&q=80",
        "images": ["https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=500&auto=format&fit=crop&q=80"],
        "description": "Second-generation antihistamine providing 24-hour relief from seasonal allergies, sneezing, and runny nose.",
        "status": "In Stock",
        "uses": ["Allergic Rhinitis", "Sneezing", "Runny Nose", "Skin Itching"],
        "precautions": ["May cause mild drowsiness in some individuals"],
        "storageInstructions": "Store in a cool, dry place away from moisture.",
        "rxRequired": False,
    },
    {
        "name": "Pantoprazole 40",
        "genericName": "Pantoprazole",
        "activeIngredient": "Pantoprazole",
        "scientificName": "(RS)-6-(difluoromethoxy)-2-[(3,4-dimethoxypyridin-2-yl)methylsulfinyl]-1H-benzo[d]imidazole",
        "category": "Gastric/Acidity",
        "strength": "40 mg",
        "form": "Tablet",
        "quantity": 50,
        "price": 45,
        "originalPrice": 58,
        "discount": "22% OFF",
        "stock": 50,
        "brand": "Pan 40 / GastroFix",
        "aliases": ["Pan 40", "Pantocid", "Pantoprazole", "Pan", "GastroFix"],
        "searchKeywords": ["pan 40", "pantoprazole", "acidity", "gas", "gerd", "heartburn", "gastric"],
        "manufacturer": "Alkem Laboratories",
        "batchNumber": "PAN-40-04",
        "manufacturingDate": datetime(2026, 1, 1, tzinfo=timezone.utc),
        "expiryDate": datetime(2028, 1, 1, tzinfo=timezone.utc),
        "image": "https://images.unsplash.com/photo-1550572017-ed24c44933ff?w=500&auto=format&fit=crop&q=80",
        "images": ["https://images.unsplash.com/photo-1550572017-ed24c44933ff?w=500&auto=format&fit=crop&q=80"],
        "description": "Proton-pump inhibitor for acid reflux, heartburn, and peptic ulcer relief.",
        "status": "In Stock",
        "uses": ["Gastroesophageal Reflux Disease (GERD)", "Heartburn", "Stomach Acidity"],
        "precautions": ["Take 30-60 minutes before breakfast for optimal efficacy"],
        "storageInstructions": "Store below 25°C protected from light.",
        "rxRequired": False,
    },
    {
        "name": "Omeprazole 20",
        "genericName": "Omeprazole",
        "activeIngredient": "Omeprazole",
        "scientificName": "(RS)-5-methoxy-2-[(4-methoxy-3,5-dimethylpyridin-2-yl)methylsulfinyl]-1H-benzimidazole",
        "category": "Gastric/Acidity",
        "strength": "20 mg",
        "form": "Capsule",
        "quantity": 50,
        "price": 35,
        "originalPrice": 45,
        "discount": "22% OFF",
        "stock": 50,
        "brand": "Omez 20 / Dr. Reddy",
        "aliases": ["Omez", "Omez 20", "Omeprazole", "OmezCare"],
        "searchKeywords": ["omez", "omeprazole", "acidity", "stomach ache", "acid reflux", "gastric"],
        "manufacturer": "Dr. Reddy Laboratories",
        "batchNumber": "OMP-20-05",
        "manufacturingDate": datetime(2026, 1, 1, tzinfo=timezone.utc),
        "expiryDate": datetime(2028, 1, 1, tzinfo=timezone.utc),
        "image": "https://images.unsplash.com/photo-1628771065518-0d82f1938462?w=500&auto=format&fit=crop&q=80",
        "images": ["https://images.unsplash.com/photo-1628771065518-0d82f1938462?w=500&auto=format&fit=crop&q=80"],
        "description": "Delayed-release capsule that reduces stomach acid for acidity and gastric comfort.",
        "status": "In Stock",
        "uses": ["Acid Reflux", "Dyspepsia", "Gastric Ulcer Prevention"],
        "precautions": ["Swallow whole; do not crush or chew capsule"],
        "storageInstructions": "Store in airtight container below 25°C.",
        "rxRequired": False,
    },
    {
        "name": "ORS Sachet",
        "genericName": "Oral Rehydration Salts",
        "activeIngredient": "Oral Rehydration Salts",
        "scientificName": "Sodium Chloride, Potassium Chloride, Sodium Citrate, Anhydrous Dextrose",
        "category": "Rehydration",
        "strength": "21.8 g",
        "form": "Sachet",
        "quantity": 100,
        "price": 20,
        "originalPrice": 24,
        "discount": "16% OFF",
        "stock": 100,
        "brand": "Electral / WHO Formula",
        "aliases": ["Electral", "ORS", "Oral Rehydration Salts", "HydroRestore"],
        "searchKeywords": ["ors", "electral", "dehydration", "diarrhea", "electrolyte", "energy powder"],
        "manufacturer": "FDC Limited",
        "batchNumber": "ORS-100-06",
        "manufacturingDate": datetime(2026, 1, 1, tzinfo=timezone.utc),
        "expiryDate": datetime(2028, 1, 1, tzinfo=timezone.utc),
        "image": "https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=500&auto=format&fit=crop&q=80",
        "images": ["https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=500&auto=format&fit=crop&q=80"],
        "description": "WHO-formulated electrolyte powder for rapid restoration of fluids and essential salts during dehydration.",
        "status": "In Stock",
        "uses": ["Dehydration", "Diarrhea Recovery", "Electrolyte Balance", "Heat Fatigue"],
        "precautions": ["Dissolve in exact recommended quantity of clean drinking water"],
        "storageInstructions": "Store in a cool dry place.",
        "rxRequired": False,
    },
    {
        "name": "Azithromycin 500",
        "genericName": "Azithromycin",
        "activeIngredient": "Azithromycin",
        "scientificName": "Azithromycin dihydrate",
        "category": "Antibiotic",
        "strength": "500 mg",
        "form": "Tablet",
        "quantity": 30,
        "price": 120,
        "originalPrice": 150,
        "discount": "20% OFF",
        "stock": 30,
        "brand": "Azithral 500 / Alembic",
        "aliases": ["Azithral", "Azithral 500", "Azithromycin", "AziShield"],
        "searchKeywords": ["azithromycin", "azithral", "antibiotic", "throat infection", "chest infection", "bacterial"],
        "manufacturer": "Alembic Pharmaceuticals",
        "batchNumber": "AZM-500-07",
        "manufacturingDate": datetime(2026, 1, 1, tzinfo=timezone.utc),
        "expiryDate": datetime(2028, 1, 1, tzinfo=timezone.utc),
        "image": "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500&auto=format&fit=crop&q=80",
        "images": ["https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500&auto=format&fit=crop&q=80"],
        "description": "Broad-spectrum macrolide antibiotic for respiratory tract and soft tissue bacterial infections.",
        "status": "In Stock",
        "uses": ["Respiratory Infections", "Bacterial Pharyngitis", "Sinusitis"],
        "precautions": ["Complete full course prescribed by physician"],
        "storageInstructions": "Store below 25°C.",
        "rxRequired": True,
    },
    {
        "name": "Amoxicillin 500",
        "genericName": "Amoxicillin",
        "activeIngredient": "Amoxicillin",
        "scientificName": "Amoxicillin Trihydrate",
        "category": "Antibiotic",
        "strength": "500 mg",
        "form": "Capsule",
        "quantity": 30,
        "price": 90,
        "originalPrice": 115,
        "discount": "21% OFF",
        "stock": 30,
        "brand": "Mox 500 / Sun Pharma",
        "aliases": ["Mox", "Mox 500", "Amoxicillin", "Amoxil", "AmoxiCure"],
        "searchKeywords": ["amoxicillin", "mox 500", "antibiotic", "ear infection", "throat infection", "chest infection"],
        "manufacturer": "Sun Pharma Laboratories",
        "batchNumber": "AMX-500-08",
        "manufacturingDate": datetime(2026, 1, 1, tzinfo=timezone.utc),
        "expiryDate": datetime(2028, 1, 1, tzinfo=timezone.utc),
        "image": "https://images.unsplash.com/photo-1577401239170-897942555fb3?w=500&auto=format&fit=crop&q=80",
        "images": ["https://images.unsplash.com/photo-1577401239170-897942555fb3?w=500&auto=format&fit=crop&q=80"],
        "description": "Broad-spectrum penicillin antibiotic effective against ear, throat, and chest bacterial infections.",
        "status": "In Stock",
        "uses": ["Bacterial Infections", "Strep Throat", "Ear Infection", "Chest Infection"],
        "precautions": ["Do not use if allergic to penicillin or beta-lactams"],
        "storageInstructions": "Store below 25°C in a dry place.",
        "rxRequired": True,
    },
    {
        "name": "Ibuprofen 400",
        "genericName": "Ibuprofen",
        "activeIngredient": "Ibuprofen",
        "scientificName": "(RS)-2-(4-(2-methylpropyl)phenyl)propanoic acid",
        "category": "Pain & Inflammation",
        "strength": "400 mg",
        "form": "Tablet",
        "quantity": 50,
        "price": 40,
        "originalPrice": 50,
        "discount": "20% OFF",
        "stock": 50,
        "brand": "Brufen 400 / Abbott",
        "aliases": ["Brufen", "Brufen 400", "Ibuprofen", "BrufenCare"],
        "searchKeywords": ["ibuprofen", "brufen", "joint pain", "muscle pain", "dental pain", "inflammation", "swelling"],
        "manufacturer": "Abbott Healthcare",
        "batchNumber": "IBU-400-09",
        "manufacturingDate": datetime(2026, 1, 1, tzinfo=timezone.utc),
        "expiryDate": datetime(2028, 1, 1, tzinfo=timezone.utc),
        "image": "https://images.unsplash.com/photo-1550572017-4fcdbb590e5b?w=500&auto=format&fit=crop&q=80",
        "images": ["https://images.unsplash.com/photo-1550572017-4fcdbb590e5b?w=500&auto=format&fit=crop&q=80"],
        "description": "Non-steroidal anti-inflammatory drug (NSAID) for muscle pain, dental ache, and swelling.",
        "status": "In Stock",
        "uses": ["Joint Pain", "Muscle Pain", "Dental Ache", "Inflammation"],
        "precautions": ["Take after food to avoid gastric irritation"],
        "storageInstructions": "Store below 25°C.",
        "rxRequired": False,
    },
    {
        "name": "Diclofenac 50",
        "genericName": "Diclofenac",
        "activeIngredient": "Diclofenac",
        "scientificName": "2-[2-(2,6-dichloroanilino)phenyl]acetic acid",
        "category": "Pain & Inflammation",
        "strength": "50 mg",
        "form": "Tablet",
        "quantity": 50,
        "price": 35,
        "originalPrice": 45,
        "discount": "22% OFF",
        "stock": 50,
        "brand": "Voveran 50 / Novartis",
        "aliases": ["Voveran", "Voveran 50", "Diclofenac", "DicloFast"],
        "searchKeywords": ["diclofenac", "voveran", "severe pain", "arthritis", "back pain", "joint pain"],
        "manufacturer": "Novartis India",
        "batchNumber": "DIC-50-10",
        "manufacturingDate": datetime(2026, 1, 1, tzinfo=timezone.utc),
        "expiryDate": datetime(2028, 1, 1, tzinfo=timezone.utc),
        "image": "https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?w=500&auto=format&fit=crop&q=80",
        "images": ["https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?w=500&auto=format&fit=crop&q=80"],
        "description": "Potent NSAID formulation for severe joint inflammation, back pain, and arthritis.",
        "status": "In Stock",
        "uses": ["Severe Body Pain", "Rheumatoid Arthritis", "Osteoarthritis", "Back Pain"],
        "precautions": ["Use shortest effective duration; take with food"],
        "storageInstructions": "Store in a dry place protected from light.",
        "rxRequired": True,
    },
    {
        "name": "Levocetirizine 5",
        "genericName": "Levocetirizine",
        "activeIngredient": "Levocetirizine",
        "scientificName": "2-[2-[4-[(R)-(4-chlorophenyl)-phenylmethyl]piperazin-1-yl]ethoxy]acetic acid",
        "category": "Allergy",
        "strength": "5 mg",
        "form": "Tablet",
        "quantity": 50,
        "price": 45,
        "originalPrice": 58,
        "discount": "22% OFF",
        "stock": 50,
        "brand": "Levocet / Cipla",
        "aliases": ["Levocet", "Levocet 5", "Levocetirizine", "L-Cetridoc"],
        "searchKeywords": ["levocetirizine", "levocet", "allergy", "cold", "sneezing", "hives", "skin allergy"],
        "manufacturer": "Cipla Limited",
        "batchNumber": "LVC-5-11",
        "manufacturingDate": datetime(2026, 1, 1, tzinfo=timezone.utc),
        "expiryDate": datetime(2028, 1, 1, tzinfo=timezone.utc),
        "image": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80",
        "images": ["https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80"],
        "description": "High-affinity active enantiomer of cetirizine for rapid relief from allergic symptoms.",
        "status": "In Stock",
        "uses": ["Chronic Urticaria", "Allergic Sneezing", "Watery Eyes", "Skin Hives"],
        "precautions": ["Avoid driving or operating heavy machinery if feeling drowsy"],
        "storageInstructions": "Store below 30°C.",
        "rxRequired": False,
    },
    {
        "name": "Metformin 500",
        "genericName": "Metformin",
        "activeIngredient": "Metformin",
        "scientificName": "1,1-dimethylbiguanide hydrochloride",
        "category": "Diabetes",
        "strength": "500 mg",
        "form": "Tablet",
        "quantity": 100,
        "price": 50,
        "originalPrice": 65,
        "discount": "23% OFF",
        "stock": 100,
        "brand": "Glycomet 500 / USV",
        "aliases": ["Glycomet", "Glycomet 500", "Metformin", "GlucoReg"],
        "searchKeywords": ["metformin", "glycomet", "diabetes", "blood sugar", "sugar control"],
        "manufacturer": "USV Private Limited",
        "batchNumber": "MET-500-12",
        "manufacturingDate": datetime(2026, 1, 1, tzinfo=timezone.utc),
        "expiryDate": datetime(2028, 1, 1, tzinfo=timezone.utc),
        "image": "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=500&auto=format&fit=crop&q=80",
        "images": ["https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=500&auto=format&fit=crop&q=80"],
        "description": "First-line oral biguanide medication for glycemic control in Type 2 Diabetes.",
        "status": "In Stock",
        "uses": ["Type 2 Diabetes Mellitus", "Glycemic Control", "Insulin Sensitivity Support"],
        "precautions": ["Take with or immediately after meals to reduce gastrointestinal discomfort"],
        "storageInstructions": "Store below 25°C in a moisture-free area.",
        "rxRequired": True,
    },
    {
        "name": "Amlodipine 5",
        "genericName": "Amlodipine",
        "activeIngredient": "Amlodipine",
        "scientificName": "(RS)-3-ethyl 5-methyl 2-[(2-aminoethoxy)methyl]-4-(2-chlorophenyl)-6-methyl-1,4-dihydropyridine-3,5-dicarboxylate",
        "category": "Blood Pressure",
        "strength": "5 mg",
        "form": "Tablet",
        "quantity": 100,
        "price": 35,
        "originalPrice": 45,
        "discount": "22% OFF",
        "stock": 100,
        "brand": "Amlong 5 / Micro Labs",
        "aliases": ["Amlong", "Amlong 5", "Amlodipine", "CardioPress"],
        "searchKeywords": ["amlodipine", "amlong", "blood pressure", "bp", "hypertension", "heart"],
        "manufacturer": "Micro Labs Limited",
        "batchNumber": "AML-5-13",
        "manufacturingDate": datetime(2026, 1, 1, tzinfo=timezone.utc),
        "expiryDate": datetime(2028, 1, 1, tzinfo=timezone.utc),
        "image": "https://images.unsplash.com/photo-1550572017-ed24c44933ff?w=500&auto=format&fit=crop&q=80",
        "images": ["https://images.unsplash.com/photo-1550572017-ed24c44933ff?w=500&auto=format&fit=crop&q=80"],
        "description": "Long-acting calcium channel blocker used in the management of hypertension and angina.",
        "status": "In Stock",
        "uses": ["Hypertension (High Blood Pressure)", "Chronic Stable Angina"],
        "precautions": ["Regular blood pressure monitoring recommended; do not stop abruptly"],
        "storageInstructions": "Store below 25°C.",
        "rxRequired": True,
    },
    {
        "name": "Losartan 50",
        "genericName": "Losartan",
        "activeIngredient": "Losartan",
        "scientificName": "[2-butyl-5-chloro-3-[[4-[2-(2H-tetrazol-5-yl)phenyl]phenyl]methyl]imidazol-4-yl]methanol",
        "category": "Blood Pressure",
        "strength": "50 mg",
        "form": "Tablet",
        "quantity": 50,
        "price": 60,
        "originalPrice": 75,
        "discount": "20% OFF",
        "stock": 50,
        "brand": "Losar 50 / Unichem",
        "aliases": ["Losar", "Losar 50", "Losartan", "VasoProtect"],
        "searchKeywords": ["losartan", "losar", "blood pressure", "bp", "hypertension", "kidney protection"],
        "manufacturer": "Unichem Laboratories",
        "batchNumber": "LOS-50-14",
        "manufacturingDate": datetime(2026, 1, 1, tzinfo=timezone.utc),
        "expiryDate": datetime(2028, 1, 1, tzinfo=timezone.utc),
        "image": "https://images.unsplash.com/photo-1585435557343-3b092031a831?w=500&auto=format&fit=crop&q=80",
        "images": ["https://images.unsplash.com/photo-1585435557343-3b092031a831?w=500&auto=format&fit=crop&q=80"],
        "description": "Angiotensin II receptor antagonist (ARB) for hypertension and renal protection.",
        "status": "In Stock",
        "uses": ["Hypertension", "Diabetic Nephropathy Support", "Cardiovascular Risk Reduction"],
        "precautions": ["Contraindicated during pregnancy; check serum potassium levels periodically"],
        "storageInstructions": "Store in airtight container below 25°C.",
        "rxRequired": True,
    },
    {
        "name": "Atorvastatin 10",
        "genericName": "Atorvastatin",
        "activeIngredient": "Atorvastatin",
        "scientificName": "(3R,5R)-7-[2-(4-fluorophenyl)-3-phenyl-4-(phenylcarbamoyl)-5-propan-2-ylpyrrol-1-yl]-3,5-dihydroxyheptanoic acid",
        "category": "Cholesterol",
        "strength": "10 mg",
        "form": "Tablet",
        "quantity": 50,
        "price": 55,
        "originalPrice": 70,
        "discount": "21% OFF",
        "stock": 50,
        "brand": "Atorva 10 / Zydus",
        "aliases": ["Atorva", "Atorva 10", "Atorvastatin", "LipidNorm"],
        "searchKeywords": ["atorvastatin", "atorva", "cholesterol", "triglycerides", "lipid", "heart health"],
        "manufacturer": "Zydus Lifesciences",
        "batchNumber": "ATV-10-15",
        "manufacturingDate": datetime(2026, 1, 1, tzinfo=timezone.utc),
        "expiryDate": datetime(2028, 1, 1, tzinfo=timezone.utc),
        "image": "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500&auto=format&fit=crop&q=80",
        "images": ["https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500&auto=format&fit=crop&q=80"],
        "description": "HMG-CoA reductase inhibitor (statin) for lowering LDL cholesterol and triglycerides.",
        "status": "In Stock",
        "uses": ["Hypercholesterolemia", "Dyslipidemia", "Prevention of Cardiovascular Events"],
        "precautions": ["Take preferably at evening bedtime; avoid excessive grapefruit consumption"],
        "storageInstructions": "Store below 25°C.",
        "rxRequired": True,
    },
    {
        "name": "Ondansetron 4",
        "genericName": "Ondansetron",
        "activeIngredient": "Ondansetron",
        "scientificName": "(RS)-9-methyl-3-[(2-methyl-1H-imidazol-1-yl)methyl]-2,3-dihydro-1H-carbazol-4-one",
        "category": "Anti-nausea",
        "strength": "4 mg",
        "form": "Tablet",
        "quantity": 30,
        "price": 40,
        "originalPrice": 50,
        "discount": "20% OFF",
        "stock": 30,
        "brand": "Emeset 4 / Cipla",
        "aliases": ["Emeset", "Emeset 4", "Ondansetron", "VomiSoothe"],
        "searchKeywords": ["ondansetron", "emeset", "vomiting", "nausea", "motion sickness", "stomach upset"],
        "manufacturer": "Cipla Limited",
        "batchNumber": "OND-4-16",
        "manufacturingDate": datetime(2026, 1, 1, tzinfo=timezone.utc),
        "expiryDate": datetime(2028, 1, 1, tzinfo=timezone.utc),
        "image": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80",
        "images": ["https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80"],
        "description": "Serotonin 5-HT3 receptor antagonist for nausea and vomiting control.",
        "status": "In Stock",
        "uses": ["Nausea and Vomiting Prevention", "Post-operative Emesis", "Gastroenteritis Emesis"],
        "precautions": ["Take 30 minutes before food or as directed by physician"],
        "storageInstructions": "Store protected from light and moisture.",
        "rxRequired": True,
    },
    {
        "name": "Dextromethorphan Syrup",
        "genericName": "Dextromethorphan",
        "activeIngredient": "Dextromethorphan Hydrobromide",
        "scientificName": "(4bS,8aR,9S)-3-methoxy-11-methyl-6,7,8,8a,9,10-hexahydro-5H-9,4b-(epiminoethano)phenanthrene",
        "category": "Cough",
        "strength": "10 mg/5ml",
        "form": "Syrup",
        "quantity": 20,
        "price": 85,
        "originalPrice": 110,
        "discount": "22% OFF",
        "stock": 20,
        "brand": "TussinClear / Benadryl DR",
        "aliases": ["TussinClear", "Dextromethorphan", "Cough Syrup", "Benadryl DR"],
        "searchKeywords": ["dextromethorphan", "cough syrup", "dry cough", "throat irritation", "cough relief"],
        "manufacturer": "Johnson & Johnson Healthcare",
        "batchNumber": "DXM-100-17",
        "manufacturingDate": datetime(2026, 1, 1, tzinfo=timezone.utc),
        "expiryDate": datetime(2028, 1, 1, tzinfo=timezone.utc),
        "image": "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80",
        "images": ["https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80"],
        "description": "Centrally-acting antitussive cough suppressant for dry, non-productive cough relief.",
        "status": "In Stock",
        "uses": ["Dry Cough", "Throat Tickle Suppression", "Irritant-Induced Cough"],
        "precautions": ["Not recommended for persistent productive wet cough with excess mucus"],
        "storageInstructions": "Store below 25°C; do not freeze.",
        "rxRequired": False,
    },
    {
        "name": "Antacid Suspension",
        "genericName": "Aluminium + Magnesium Hydroxide",
        "activeIngredient": "Aluminium Hydroxide, Magnesium Hydroxide, Simethicone",
        "scientificName": "Aluminium Hydroxide + Magnesium Hydroxide + Dimethicone",
        "category": "Acidity",
        "strength": "200 ml",
        "form": "Suspension",
        "quantity": 20,
        "price": 90,
        "originalPrice": 115,
        "discount": "21% OFF",
        "stock": 20,
        "brand": "Gelusil MPS / Digene",
        "aliases": ["Gelusil", "Digene", "Antacid Suspension", "AcidiRelief Gel"],
        "searchKeywords": ["gelusil", "digene", "antacid", "acidity", "gas relief", "heartburn", "stomach burning"],
        "manufacturer": "Pfizer India",
        "batchNumber": "ANT-200-18",
        "manufacturingDate": datetime(2026, 1, 1, tzinfo=timezone.utc),
        "expiryDate": datetime(2028, 1, 1, tzinfo=timezone.utc),
        "image": "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80",
        "images": ["https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80"],
        "description": "Fast-acting soothing liquid antacid neutralizing excess stomach acid and alleviating bloating.",
        "status": "In Stock",
        "uses": ["Heartburn", "Acid Indigestion", "Flatulence & Bloating", "Sour Stomach"],
        "precautions": ["Shake well before use; take after meals and at bedtime"],
        "storageInstructions": "Store below 25°C in tightly closed bottle.",
        "rxRequired": False,
    },
    {
        "name": "Vitamin B-Complex",
        "genericName": "B Vitamins",
        "activeIngredient": "Thiamine, Riboflavin, Niacinamide, Pyridoxine, Cyanocobalamin",
        "scientificName": "Multivitamin B-Complex with Zinc & Folic Acid",
        "category": "Supplement",
        "strength": "High Potency",
        "form": "Tablet",
        "quantity": 100,
        "price": 70,
        "originalPrice": 90,
        "discount": "22% OFF",
        "stock": 100,
        "brand": "Becosules / Pfizer",
        "aliases": ["Becosules", "B-Complex", "Vitamin B", "NutriB Boost"],
        "searchKeywords": ["becosules", "vitamin b", "b complex", "mouth ulcers", "energy", "weakness", "supplement"],
        "manufacturer": "Pfizer Healthcare",
        "batchNumber": "VBC-100-19",
        "manufacturingDate": datetime(2026, 1, 1, tzinfo=timezone.utc),
        "expiryDate": datetime(2028, 1, 1, tzinfo=timezone.utc),
        "image": "https://images.unsplash.com/photo-1563213126-a4273aed2016?w=500&auto=format&fit=crop&q=80",
        "images": ["https://images.unsplash.com/photo-1563213126-a4273aed2016?w=500&auto=format&fit=crop&q=80"],
        "description": "Essential Vitamin B complex with Zinc and Vitamin C for cellular energy metabolism and immune vitality.",
        "status": "In Stock",
        "uses": ["Nutritional Deficiency", "Mouth Ulcer Relief", "Immune Support", "Energy Metabolism"],
        "precautions": ["Take daily with plenty of water after food"],
        "storageInstructions": "Store below 25°C away from moisture.",
        "rxRequired": False,
    },
    {
        "name": "Calcium + Vitamin D3",
        "genericName": "Calcium + Vitamin D3",
        "activeIngredient": "Calcium Carbonate, Cholecalciferol (Vitamin D3)",
        "scientificName": "Calcium Carbonate 500mg + Vitamin D3 250 IU",
        "category": "Supplement",
        "strength": "500 mg + 250 IU",
        "form": "Tablet",
        "quantity": 100,
        "price": 100,
        "originalPrice": 130,
        "discount": "23% OFF",
        "stock": 100,
        "brand": "Shelcal 500 / Torrent",
        "aliases": ["Shelcal", "Shelcal 500", "Calcium D3", "CalciBone"],
        "searchKeywords": ["shelcal", "calcium", "vitamin d3", "bone strength", "joint health", "supplement"],
        "manufacturer": "Torrent Pharmaceuticals",
        "batchNumber": "CAL-500-20",
        "manufacturingDate": datetime(2026, 1, 1, tzinfo=timezone.utc),
        "expiryDate": datetime(2028, 1, 1, tzinfo=timezone.utc),
        "image": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80",
        "images": ["https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80"],
        "description": "High-absorption calcium with Vitamin D3 for optimal bone mineral density and joint strength.",
        "status": "In Stock",
        "uses": ["Osteoporosis Prevention", "Bone Density Support", "Calcium Deficiency", "Joint Strength"],
        "precautions": ["Do not exceed recommended daily allowance; drink adequate water"],
        "storageInstructions": "Store in a cool dry place away from sunlight.",
        "rxRequired": False,
    },
]


def extract_medicine_name(raw_query: str) -> str:
    """
    Extracts candidate medicine or brand name from conversational phrases:
    e.g. 'Tell me about Dolo' -> 'dolo'
    'tell about dolo' -> 'dolo'
    'Show me paracetamol 650' -> 'paracetamol 650'
    'Do you have Pantoprazole?' -> 'pantoprazole'
    """
    if not raw_query:
        return ""
    q = raw_query.strip().lower()

    # Normalize spoken numbers
    q = re.sub(r'\bsix fifty\b', '650', q)
    q = re.sub(r'\bfive hundred\b', '500', q)
    q = re.sub(r'\bforty\b', '40', q)
    q = re.sub(r'\btwenty\b', '20', q)
    q = re.sub(r'\bthirty\b', '30', q)
    q = re.sub(r'\bfifty\b', '50', q)
    q = re.sub(r'\bten\b', '10', q)
    q = re.sub(r'\bfive\b', '5', q)
    q = re.sub(r'\bfour\b', '4', q)
    q = re.sub(r'[?.!,;:\'"()]', '', q).strip()

    prefix_patterns = [
        r'^(?:hey\s+)?(?:jarvis\s*,?\s*)?',
        r'^(?:can\s+you\s+(?:please\s+)?|could\s+you\s+(?:please\s+)?|please\s+)?',
        r'^(?:tell\s+(?:me|us)?\s*(?:something\s+)?(?:about)?|explain\s+(?:to\s+(?:me|us)\s+)?(?:about)?|describe|talk\s+about)\s+',
        r'^(?:what\s+(?:is|are|about)|whats\s+(?:about)?|how\s+about|know\s+about|learn\s+about)\s+',
        r'^(?:i\s+(?:want|need)\s+(?:to\s+know\s+(?:about)?|to\s+buy|to\s+find|to\s+get|info\s+on|details\s+of)?)\s+',
        r'^(?:give\s+(?:me|us)?\s*(?:some\s+)?(?:info|information|details)?\s*(?:about|on|of)?)\s+',
        r'^(?:information\s+(?:about|on|of)|info\s+(?:about|on|of)|details\s+(?:about|on|of)|detail\s+(?:about|on|of))\s+',
        r'^(?:show\s+(?:me|us)?|find\s+(?:me|us)?|buy|get|search\s+(?:for)?|lookup|look\s+for|check\s+(?:for)?)\s+',
        r'^(?:do\s+you\s+have|do\s+we\s+have|is\s+there\s+any|are\s+there\s+any|is\s+there|got\s+any)\s+',
        r'^(?:now\s+show\s+me|something\s+for|medicines?\s+for|tablets?\s+for|tablets?\s+of|capsules?\s+of|capsules?\s+for|syrup\s+for|syrup\s+of)\s+',
        r'^(?:about|a|an|the)\s+',
    ]

    for _ in range(4):
        prev = q
        for pat in prefix_patterns:
            q = re.sub(pat, '', q, flags=re.IGNORECASE).strip()
        if prev == q:
            break

    # Trailing suffixes
    q = re.sub(r'\s+(?:used for|uses|usage|indications?|price|cost|rate|pricing|available|in stock|stock|tablets?|capsules?|syrup|suspension|sachet|medicines?|drugs?|products?|please|thanks?|thank you|jarvis)$', '', q, flags=re.IGNORECASE).strip()
    q = re.sub(r'^(?:a|an|the|about)\s+', '', q, flags=re.IGNORECASE).strip()

    return q


def format_medicine_item(m: Dict[str, Any], idx: int = 1) -> Dict[str, Any]:
    raw_id = str(m.get("_id", m.get("id", f"med_{idx}")))
    return {
        "id": raw_id,
        "_id": raw_id,
        "rawId": raw_id,
        "name": m.get("name", "Medicine"),
        "genericName": m.get("genericName", ""),
        "activeIngredient": m.get("activeIngredient", m.get("genericName", "")),
        "scientificName": m.get("scientificName", ""),
        "brand": m.get("brand", "PharmaCare Labs"),
        "aliases": m.get("aliases", []),
        "category": m.get("category", "General"),
        "strength": m.get("strength", ""),
        "form": m.get("form", "Tablet"),
        "quantity": int(m.get("quantity", m.get("stock", 50))),
        "price": float(m.get("price", 50)),
        "originalPrice": float(m.get("originalPrice", round(float(m.get("price", 50)) * 1.25))),
        "discount": m.get("discount", "15% OFF"),
        "stock": int(m.get("stock", 50)),
        "manufacturer": m.get("manufacturer", "PharmaCare Laboratories"),
        "batchNumber": m.get("batchNumber", "PCM-2026"),
        "manufacturingDate": m.get("manufacturingDate"),
        "expiryDate": m.get("expiryDate"),
        "expiryStatus": "VALID",
        "isExpired": False,
        "image": m.get("image", "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80"),
        "images": m.get("images", [m.get("image", "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80")]),
        "description": m.get("description", ""),
        "status": m.get("status", "In Stock"),
        "uses": m.get("uses", []),
        "precautions": m.get("precautions", []),
        "storageInstructions": m.get("storageInstructions", "Store in a cool dry place."),
        "rxRequired": bool(m.get("rxRequired", False)),
        "productType": "Medicine",
    }
