import mongoose from 'mongoose';
import dotenv from 'dotenv';
import bcrypt from 'bcryptjs';
import dns from 'dns';

// Fix Windows DNS SRV resolution for MongoDB Atlas
try {
  dns.setServers(['8.8.8.8', '1.1.1.1']);
} catch (e) {
  // Ignore
}

import User from './models/User.js';
import Medicine from './models/Medicine.js';
import HealthProduct from './models/HealthProduct.js';
import PersonalCareProduct from './models/PersonalCareProduct.js';
import Cart from './models/Cart.js';
import Order from './models/Order.js';

dotenv.config();

// Curated authentic product images with verified CDN links
const IMAGES = {
  amoxicillin: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
  paracetamol: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80',
  metformin: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=500&auto=format&fit=crop&q=80',
  atorvastatin: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500&auto=format&fit=crop&q=80',
  azithromycin: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=500&auto=format&fit=crop&q=80',
  pantoprazole: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=500&auto=format&fit=crop&q=80',
  cetirizine: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=500&auto=format&fit=crop&q=80',
  ibuprofen: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80',
  multivitamin: 'https://images.unsplash.com/photo-1577401239170-897942555fb3?w=500&auto=format&fit=crop&q=80',
  bpMonitor: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?w=500&auto=format&fit=crop&q=80',
  glucometer: 'https://images.unsplash.com/photo-1612277795421-9bc7706a4a34?w=500&auto=format&fit=crop&q=80',
  omega3: 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=500&auto=format&fit=crop&q=80',
  vitaminD3: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
  oximeter: 'https://images.unsplash.com/photo-1631815589968-fdb09a223b1e?w=500&auto=format&fit=crop&q=80',
  faceWash: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=500&auto=format&fit=crop&q=80',
  ceramideSerum: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=500&auto=format&fit=crop&q=80',
  sunscreen: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=500&auto=format&fit=crop&q=80',
  shampoo: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=500&auto=format&fit=crop&q=80',
  hairOil: 'https://images.unsplash.com/photo-1608248597359-28c0c45d3153?w=500&auto=format&fit=crop&q=80',
  bodyLotion: 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=500&auto=format&fit=crop&q=80',
  thermometer: 'https://images.unsplash.com/photo-1584634731339-252c581abfc5?w=500&auto=format&fit=crop&q=80',
  dolo: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80',
  ayurveda: 'https://images.unsplash.com/photo-1617897903246-719242758050?w=500&auto=format&fit=crop&q=80',
  protein: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=500&auto=format&fit=crop&q=80',
};

const medicinesData = [
  {
    name: 'Dolo 650',
    genericName: 'Paracetamol',
    scientificName: 'N-(4-hydroxyphenyl)acetamide',
    brand: 'Dolo',
    composition: 'Paracetamol IP (650mg)',
    strength: '650mg',
    description: 'Trusted antipyretic and pain reliever tablet for symptomatic relief of high fever, body pain, and headaches.',
    uses: ['Fever Reduction', 'Headaches', 'Body Pain', 'Post-Vaccination Fever'],
    precautions: ['Do not exceed 4000mg in 24 hours', 'Keep 4-6 hours interval between doses'],
    storageInstructions: 'Store below 25°C in a dry place protected from moisture.',
    manufacturingDate: new Date('2026-01-20'),
    expiryDate: new Date('2028-01-20'),
    batchNumber: 'DOL-650-301',
    price: 35,
    originalPrice: 42,
    discount: '16% OFF',
    stock: 200,
    category: 'Over-The-Counter (OTC)',
    rxRequired: false,
    image: IMAGES.dolo,
  },
  {
    name: 'Paracetamol 650mg Extra Relief',
    genericName: 'Paracetamol',
    scientificName: 'N-(4-hydroxyphenyl)acetamide',
    brand: 'Aegis Consumer Healthcare',
    composition: 'Paracetamol IP (650mg)',
    strength: '650mg',
    description: 'Fast-acting analgesic and antipyretic for effective relief from fever, headaches, and body pain.',
    uses: ['Fever Reduction', 'Headache & Migraine', 'Body Aches', 'Dental Pain'],
    precautions: ['Do not exceed 4000mg in 24 hours', 'Avoid alcohol consumption with paracetamol'],
    storageInstructions: 'Store protected from light and moisture below 25°C.',
    manufacturingDate: new Date('2026-01-15'),
    expiryDate: new Date('2028-01-15'),
    batchNumber: 'PCM-650-892',
    price: 35,
    originalPrice: 45,
    discount: '22% OFF',
    stock: 250,
    category: 'Over-The-Counter (OTC)',
    rxRequired: false,
    image: IMAGES.paracetamol,
  },
  {
    name: 'Amoxicillin Trihydrate 500mg',
    genericName: 'Amoxicillin',
    scientificName: '(2S,5R,6R)-6-[[(2R)-2-amino-2-(4-hydroxyphenyl)acetyl]amino]-3,3-dimethyl-7-oxo-4-thia-1-azabicyclo[3.2.0]heptane-2-carboxylic acid',
    brand: 'Apex Pharma Bio Labs',
    composition: 'Amoxicillin Trihydrate IP equivalent to Amoxicillin 500mg',
    strength: '500mg',
    description: 'Broad-spectrum beta-lactam antibiotic used to treat bacterial infections of the respiratory tract, ear, and urinary tract.',
    uses: ['Bacterial Infections', 'Respiratory Tract Infection', 'Strep Throat'],
    precautions: ['Complete full course prescribed', 'Contraindicated in penicillin allergy'],
    storageInstructions: 'Store below 25°C in a dry place.',
    manufacturingDate: new Date('2026-01-15'),
    expiryDate: new Date('2028-01-15'),
    batchNumber: 'AMX-2026-894',
    price: 145,
    originalPrice: 180,
    discount: '19% OFF',
    stock: 85,
    category: 'Prescription (Rx)',
    rxRequired: true,
    image: IMAGES.amoxicillin,
  },
  {
    name: 'Metformin Hydrochloride 850mg',
    genericName: 'Metformin HCl',
    scientificName: '1,1-dimethylbiguanide hydrochloride',
    brand: 'GlycoCare Bio-Tech',
    composition: 'Metformin Hydrochloride IP (850mg) Sustained Release',
    strength: '850mg',
    description: 'First-line oral antidiabetic medication for managing blood glucose levels in type 2 diabetes.',
    uses: ['Type 2 Diabetes Mellitus', 'Insulin Resistance Management'],
    precautions: ['Take with meals to minimize GI distress', 'Monitor kidney function'],
    storageInstructions: 'Store in a dry place at room temperature.',
    manufacturingDate: new Date('2025-11-10'),
    expiryDate: new Date('2027-11-10'),
    batchNumber: 'MET-850-512',
    price: 98,
    originalPrice: 125,
    discount: '21% OFF',
    stock: 120,
    category: 'Chronic Care',
    rxRequired: true,
    image: IMAGES.metformin,
  },
  {
    name: 'Atorvastatin Calcium 20mg',
    genericName: 'Atorvastatin',
    scientificName: '(3R,5R)-7-[2-(4-fluorophenyl)-3-phenyl-4-(phenylcarbamoyl)-5-propan-2-ylpyrrol-1-yl]-3,5-dihydroxyheptanoic acid',
    brand: 'CardioLife Labs',
    composition: 'Atorvastatin Calcium Trihydrate IP equivalent to Atorvastatin 20mg',
    strength: '20mg',
    description: 'Statin lipid-lowering agent used to lower LDL cholesterol and reduce cardiovascular risk.',
    uses: ['Hypercholesterolemia', 'Cardiovascular Risk Reduction'],
    precautions: ['Take once daily at bedtime', 'Report unexplained muscle pain'],
    storageInstructions: 'Store below 30°C.',
    manufacturingDate: new Date('2025-10-01'),
    expiryDate: new Date('2027-10-01'),
    batchNumber: 'ATV-20-441',
    price: 210,
    originalPrice: 260,
    discount: '19% OFF',
    stock: 65,
    category: 'Chronic Care',
    rxRequired: true,
    image: IMAGES.atorvastatin,
  },
  {
    name: 'Azithromycin 500mg Tablets',
    genericName: 'Azithromycin',
    scientificName: 'Azithromycin dihydrate',
    brand: 'ZithroBio Pharmaceuticals',
    composition: 'Azithromycin Dihydrate IP equivalent to Azithromycin 500mg',
    strength: '500mg',
    description: 'Macrolide antibiotic used for respiratory tract, throat, and skin bacterial infections.',
    uses: ['Chest Infections', 'Bronchitis', 'Sinusitis', 'Skin Infections'],
    precautions: ['Take 1 hour before or 2 hours after food'],
    storageInstructions: 'Store protected from moisture.',
    manufacturingDate: new Date('2026-01-20'),
    expiryDate: new Date('2028-01-20'),
    batchNumber: 'AZI-500-109',
    price: 180,
    originalPrice: 220,
    discount: '18% OFF',
    stock: 50,
    category: 'Prescription (Rx)',
    rxRequired: true,
    image: IMAGES.azithromycin,
  },
  {
    name: 'Pantoprazole Gastro-Resistant 40mg',
    genericName: 'Pantoprazole Sodium',
    scientificName: '6-(difluoromethoxy)-2-[(3,4-dimethoxypyridin-2-yl)methylsulfinyl]-1H-benzimidazole sodium',
    brand: 'GastroShield Pharma',
    composition: 'Pantoprazole Sodium Sesquihydrate IP equivalent to Pantoprazole 40mg',
    strength: '40mg',
    description: 'Proton pump inhibitor (PPI) that decreases stomach acid production for GERD, acid reflux, and heartburn.',
    uses: ['Gastroesophageal Reflux Disease (GERD)', 'Acidity & Heartburn', 'Peptic Ulcers'],
    precautions: ['Take on an empty stomach in the morning 30 minutes before breakfast'],
    storageInstructions: 'Store in dry place.',
    manufacturingDate: new Date('2026-02-15'),
    expiryDate: new Date('2028-02-15'),
    batchNumber: 'PAN-40-781',
    price: 110,
    originalPrice: 135,
    discount: '18% OFF',
    stock: 140,
    category: 'Over-The-Counter (OTC)',
    rxRequired: false,
    image: IMAGES.pantoprazole,
  },
  {
    name: 'Cetirizine Hydrochloride 10mg',
    genericName: 'Cetirizine HCl',
    scientificName: '2-[2-[4-[(4-chlorophenyl)-phenylmethyl]piperazin-1-yl]ethoxy]acetic acid dihydrochloride',
    brand: 'AllerFree Healthcare',
    composition: 'Cetirizine Hydrochloride IP 10mg',
    strength: '10mg',
    description: 'Second-generation non-drowsy antihistamine for quick relief from sneezing, runny nose, and allergic reactions.',
    uses: ['Allergic Rhinitis', 'Urticaria (Hives)', 'Pollen & Dust Allergies'],
    precautions: ['May cause mild drowsiness in sensitive individuals'],
    storageInstructions: 'Store below 25°C.',
    manufacturingDate: new Date('2025-12-01'),
    expiryDate: new Date('2027-12-01'),
    batchNumber: 'CET-10-332',
    price: 45,
    originalPrice: 55,
    discount: '18% OFF',
    stock: 200,
    category: 'Over-The-Counter (OTC)',
    rxRequired: false,
    image: IMAGES.cetirizine,
  },
  {
    name: 'Ibuprofen 400mg Pain & Anti-Inflammatory',
    genericName: 'Ibuprofen',
    scientificName: '2-[4-(2-methylpropyl)phenyl]propanoic acid',
    brand: 'Aegis Consumer Healthcare',
    composition: 'Ibuprofen IP 400mg',
    strength: '400mg',
    description: 'Nonsteroidal anti-inflammatory drug (NSAID) for dental pain, muscular inflammation, and joint aches.',
    uses: ['Dental Pain', 'Joint Inflammation', 'Musculoskeletal Pain'],
    precautions: ['Take with food or milk to avoid gastric irritation'],
    storageInstructions: 'Store at room temperature.',
    manufacturingDate: new Date('2026-01-05'),
    expiryDate: new Date('2028-01-05'),
    batchNumber: 'IBU-400-882',
    price: 52,
    originalPrice: 65,
    discount: '20% OFF',
    stock: 160,
    category: 'Over-The-Counter (OTC)',
    rxRequired: false,
    image: IMAGES.ibuprofen,
  },
  {
    name: 'Montelukast Sodium & Levocetirizine 10mg/5mg',
    genericName: 'Montelukast + Levocetirizine',
    scientificName: 'Montelukast sodium + Levocetirizine dihydrochloride',
    brand: 'RespiraCare Bio',
    composition: 'Montelukast Sodium IP 10mg + Levocetirizine HCl IP 5mg',
    strength: '10mg / 5mg',
    description: 'Combination anti-allergic medication for prevention of asthma symptoms and allergic rhinitis relief.',
    uses: ['Allergic Asthma', 'Chronic Rhinitis', 'Seasonal Hay Fever'],
    precautions: ['Take preferably in the evening'],
    storageInstructions: 'Store in airtight containers protected from light.',
    manufacturingDate: new Date('2025-11-20'),
    expiryDate: new Date('2027-11-20'),
    batchNumber: 'MLT-105-674',
    price: 165,
    originalPrice: 205,
    discount: '19% OFF',
    stock: 75,
    category: 'Prescription (Rx)',
    rxRequired: true,
    image: IMAGES.cetirizine,
  },
  {
    name: 'Telmisartan 40mg BP Care Tablets',
    genericName: 'Telmisartan',
    scientificName: 'Telmisartan IP',
    brand: 'CardioLife Labs',
    composition: 'Telmisartan IP 40mg',
    strength: '40mg',
    description: 'Angiotensin II receptor blocker (ARB) used for the management of essential hypertension.',
    uses: ['Hypertension', 'Cardiovascular Risk Reduction'],
    precautions: ['Monitor blood pressure and serum potassium regularly'],
    storageInstructions: 'Keep blister strips in moisture-proof pack.',
    manufacturingDate: new Date('2026-01-10'),
    expiryDate: new Date('2028-01-10'),
    batchNumber: 'TEL-40-551',
    price: 130,
    originalPrice: 160,
    discount: '19% OFF',
    stock: 90,
    category: 'Chronic Care',
    rxRequired: true,
    image: IMAGES.atorvastatin,
  },
  {
    name: 'Omeprazole 20mg Acid Reflux Capsules',
    genericName: 'Omeprazole',
    scientificName: '5-methoxy-2-[(4-methoxy-3,5-dimethylpyridin-2-yl)methylsulfinyl]-1H-benzimidazole',
    brand: 'GastroShield Pharma',
    composition: 'Omeprazole IP 20mg (Enteric Coated Pellets)',
    strength: '20mg',
    description: 'Proton pump inhibitor used to treat heartburn, indigestion, and acid reflux symptoms.',
    uses: ['Heartburn', 'Acid Indigestion', 'Zollinger-Ellison Syndrome'],
    precautions: ['Swallow whole, do not chew pellets'],
    storageInstructions: 'Store in dry place.',
    manufacturingDate: new Date('2025-09-01'),
    expiryDate: new Date('2027-09-01'),
    batchNumber: 'OMP-20-912',
    price: 58,
    originalPrice: 70,
    discount: '17% OFF',
    stock: 110,
    category: 'Over-The-Counter (OTC)',
    rxRequired: false,
    image: IMAGES.pantoprazole,
  },
  {
    name: 'Ciprofloxacin 500mg Broad Spectrum',
    genericName: 'Ciprofloxacin',
    scientificName: 'Ciprofloxacin hydrochloride',
    brand: 'Apex Pharma Bio Labs',
    composition: 'Ciprofloxacin Hydrochloride IP equivalent to Ciprofloxacin 500mg',
    strength: '500mg',
    description: 'Fluoroquinolone antibiotic for bacterial urinary tract, gastrointestinal, and skin infections.',
    uses: ['Urinary Tract Infections', 'Infectious Diarrhea', 'Typhoid Fever'],
    precautions: ['Stay well-hydrated during treatment'],
    storageInstructions: 'Store below 25°C.',
    manufacturingDate: new Date('2025-08-15'),
    expiryDate: new Date('2027-08-15'),
    batchNumber: 'CIP-500-221',
    price: 115,
    originalPrice: 140,
    discount: '18% OFF',
    stock: 45,
    category: 'Prescription (Rx)',
    rxRequired: true,
    image: IMAGES.amoxicillin,
  },
  {
    name: 'Rosuvastatin 10mg Lipid Care',
    genericName: 'Rosuvastatin Calcium',
    scientificName: 'Rosuvastatin Calcium IP',
    brand: 'CardioLife Labs',
    composition: 'Rosuvastatin Calcium IP equivalent to Rosuvastatin 10mg',
    strength: '10mg',
    description: 'Potent statin medication used for lipid regulation and primary prevention of cardiovascular events.',
    uses: ['Hyperlipidemia', 'Arterial Plaque Reduction'],
    precautions: ['Periodic liver function monitoring recommended'],
    storageInstructions: 'Store protected from moisture.',
    manufacturingDate: new Date('2026-01-01'),
    expiryDate: new Date('2028-01-01'),
    batchNumber: 'RSV-10-891',
    price: 195,
    originalPrice: 245,
    discount: '20% OFF',
    stock: 80,
    category: 'Chronic Care',
    rxRequired: true,
    image: IMAGES.atorvastatin,
  },
  {
    name: 'Losartan Potassium 50mg',
    genericName: 'Losartan',
    scientificName: 'Losartan Potassium IP',
    brand: 'CardioLife Labs',
    composition: 'Losartan Potassium IP 50mg',
    strength: '50mg',
    description: 'Antihypertensive agent for management of high blood pressure and renal protection in diabetes.',
    uses: ['Hypertension', 'Diabetic Nephropathy'],
    precautions: ['Do not use in pregnancy'],
    storageInstructions: 'Store at controlled room temperature.',
    manufacturingDate: new Date('2025-10-15'),
    expiryDate: new Date('2027-10-15'),
    batchNumber: 'LOS-50-621',
    price: 85,
    originalPrice: 105,
    discount: '19% OFF',
    stock: 95,
    category: 'Chronic Care',
    rxRequired: true,
    image: IMAGES.atorvastatin,
  },
  {
    name: 'Doxycycline Hyclate 100mg',
    genericName: 'Doxycycline',
    scientificName: 'Doxycycline hyclate',
    brand: 'DermaBio Labs',
    composition: 'Doxycycline Hyclate IP equivalent to Doxycycline 100mg',
    strength: '100mg',
    description: 'Tetracycline antibiotic commonly prescribed for acne vulgaris, rosacea, and tick-borne infections.',
    uses: ['Severe Acne', 'Lyme Disease', 'Respiratory Infections'],
    precautions: ['Take with a full glass of water, do not lie down immediately'],
    storageInstructions: 'Protect from light and heat.',
    manufacturingDate: new Date('2025-07-01'),
    expiryDate: new Date('2027-07-01'),
    batchNumber: 'DOX-100-410',
    price: 95,
    originalPrice: 120,
    discount: '21% OFF',
    stock: 60,
    category: 'Prescription (Rx)',
    rxRequired: true,
    image: IMAGES.amoxicillin,
  },
  {
    name: 'Glimepiride 2mg Diabetes Care',
    genericName: 'Glimepiride',
    scientificName: 'Glimepiride IP',
    brand: 'GlycoCare Bio-Tech',
    composition: 'Glimepiride IP 2mg',
    strength: '2mg',
    description: 'Second-generation sulfonylurea that stimulates pancreatic insulin secretion.',
    uses: ['Type 2 Diabetes Mellitus'],
    precautions: ['Take with the first main meal of the day; monitor for hypoglycemia'],
    storageInstructions: 'Store below 25°C.',
    manufacturingDate: new Date('2025-11-01'),
    expiryDate: new Date('2027-11-01'),
    batchNumber: 'GLM-2-381',
    price: 75,
    originalPrice: 95,
    discount: '21% OFF',
    stock: 110,
    category: 'Chronic Care',
    rxRequired: true,
    image: IMAGES.metformin,
  },
  {
    name: 'Amlodipine Besylate 5mg',
    genericName: 'Amlodipine',
    scientificName: 'Amlodipine Besylate IP',
    brand: 'CardioLife Labs',
    composition: 'Amlodipine Besylate IP equivalent to Amlodipine 5mg',
    strength: '5mg',
    description: 'Calcium channel blocker used to treat high blood pressure and coronary artery disease.',
    uses: ['Hypertension', 'Chronic Stable Angina'],
    precautions: ['May cause ankle swelling in some individuals'],
    storageInstructions: 'Store protected from light.',
    manufacturingDate: new Date('2025-12-15'),
    expiryDate: new Date('2027-12-15'),
    batchNumber: 'AML-5-820',
    price: 48,
    originalPrice: 60,
    discount: '20% OFF',
    stock: 130,
    category: 'Chronic Care',
    rxRequired: true,
    image: IMAGES.atorvastatin,
  },
  {
    name: 'Levothyroxine Sodium 50mcg',
    genericName: 'Levothyroxine',
    scientificName: 'Levothyroxine Sodium IP',
    brand: 'EndoHealth Labs',
    composition: 'Levothyroxine Sodium IP 50mcg',
    strength: '50mcg',
    description: 'Synthetic thyroid hormone replacement for the treatment of hypothyroidism.',
    uses: ['Hypothyroidism', 'Thyroid Hormone Deficiency'],
    precautions: ['Take on empty stomach 30-60 mins before breakfast with water only'],
    storageInstructions: 'Store in a cool place protected from moisture.',
    manufacturingDate: new Date('2026-01-10'),
    expiryDate: new Date('2028-01-10'),
    batchNumber: 'THY-50-931',
    price: 135,
    originalPrice: 165,
    discount: '18% OFF',
    stock: 100,
    category: 'Chronic Care',
    rxRequired: true,
    image: IMAGES.metformin,
  },
  {
    name: 'Clopidogrel 75mg Antiplatelet',
    genericName: 'Clopidogrel',
    scientificName: 'Clopidogrel Bisulphate IP',
    brand: 'CardioLife Labs',
    composition: 'Clopidogrel Bisulphate IP equivalent to Clopidogrel 75mg',
    strength: '75mg',
    description: 'Antiplatelet agent used to prevent blood clots in coronary artery disease and peripheral vascular disease.',
    uses: ['Post-Stent Care', 'Heart Attack & Stroke Prevention'],
    precautions: ['Consult doctor before dental or surgical procedures'],
    storageInstructions: 'Store below 30°C.',
    manufacturingDate: new Date('2025-08-01'),
    expiryDate: new Date('2027-08-01'),
    batchNumber: 'CLP-75-199',
    price: 175,
    originalPrice: 220,
    discount: '20% OFF',
    stock: 70,
    category: 'Chronic Care',
    rxRequired: true,
    image: IMAGES.atorvastatin,
  },
  {
    name: 'ORS Electrolyte Hydration Formula Orange',
    genericName: 'Oral Rehydration Salts',
    scientificName: 'WHO Oral Rehydration Formula',
    brand: 'Aegis Consumer Healthcare',
    composition: 'WHO Formula: Sodium Chloride 2.6g, Potassium Chloride 1.5g, Sodium Citrate 2.9g, Dextrose 13.5g per sachet',
    strength: '21.8g Sachet',
    description: 'WHO-recommended oral rehydration formulation for rapid recovery from dehydration caused by diarrhea or heat exhaustion.',
    uses: ['Dehydration', 'Electrolyte Balance', 'Travel Recovery'],
    precautions: ['Dissolve exactly in 1 liter of clean drinking water'],
    storageInstructions: 'Store in dry place.',
    manufacturingDate: new Date('2026-02-01'),
    expiryDate: new Date('2028-02-01'),
    batchNumber: 'ORS-ORG-102',
    price: 24,
    originalPrice: 30,
    discount: '20% OFF',
    stock: 300,
    category: 'Over-The-Counter (OTC)',
    rxRequired: false,
    image: IMAGES.paracetamol,
  },

  // EXPIRED MEDICINE (For testing backend expiry validation rejection)
  {
    name: 'Expired Batch - Tetracycline 250mg (AI Test Item)',
    genericName: 'Tetracycline HCl',
    scientificName: 'Tetracycline Hydrochloride IP',
    brand: 'Legacy BioTech Demo',
    composition: 'Tetracycline Hydrochloride IP 250mg',
    strength: '250mg',
    description: 'Expired test pharmaceutical batch specifically seeded to verify backend purchase prevention and safety alerts.',
    uses: ['Expired Sample For Validation'],
    precautions: ['DO NOT INGEST - EXPIRED BATCH'],
    storageInstructions: 'Segregated quarantine rack.',
    manufacturingDate: new Date('2022-01-01'),
    expiryDate: new Date('2024-01-01'), // EXPIRED
    batchNumber: 'EXP-TET-999',
    price: 40,
    originalPrice: 50,
    discount: '20% OFF',
    stock: 15,
    category: 'Prescription (Rx)',
    rxRequired: true,
    image: IMAGES.amoxicillin,
  },
  // EXPIRING SOON MEDICINE (<90 days)
  {
    name: 'Expiring Soon - Ranitidine 150mg (AI Warning Test)',
    genericName: 'Ranitidine',
    scientificName: 'Ranitidine Hydrochloride IP',
    brand: 'Legacy BioTech Demo',
    composition: 'Ranitidine Hydrochloride IP 150mg',
    strength: '150mg',
    description: 'Expiring soon test pharmaceutical batch seeded to verify dynamic EXPIRES_SOON warning status and inventory alerts.',
    uses: ['Short-dated test batch'],
    precautions: ['Nearing expiration date threshold'],
    storageInstructions: 'Quarantine review rack.',
    manufacturingDate: new Date('2024-06-01'),
    expiryDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000), // ~45 days from now
    batchNumber: 'EXP-SOON-45D',
    price: 35,
    originalPrice: 45,
    discount: '22% OFF',
    stock: 25,
    category: 'Over-The-Counter (OTC)',
    rxRequired: false,
    image: IMAGES.pantoprazole,
  },
];

const healthProductsData = [
  {
    name: 'Vitamin D3 60,000 IU Weekly Boost',
    brand: 'Optima Nutrition',
    category: 'Supplements & Vitamins',
    description: 'High-potency Cholecalciferol chewable tablets to strengthen bone density, elevate immunity, and support mood.',
    rating: 4.9,
    reviews: 730,
    price: 180,
    originalPrice: 220,
    discount: '18% OFF',
    stock: 150,
    tag: 'Top Rated',
    image: IMAGES.vitaminD3,
  },
  {
    name: 'Vitamin D3 & K2-7 Complex 5000 IU',
    brand: 'NutriPure Labs',
    category: 'Supplements & Vitamins',
    description: 'Synergistic Vitamin D3 + Menaquinone K2 formula for cardiovascular arterial health and optimal calcium absorption.',
    rating: 4.9,
    reviews: 580,
    price: 349,
    originalPrice: 450,
    discount: '22% OFF',
    stock: 120,
    tag: 'Clinical Choice',
    image: IMAGES.vitaminD3,
  },
  {
    name: 'Optima Multivitamin AI Gold (60 Tabs)',
    brand: 'Optima Nutrition',
    category: 'Supplements & Vitamins',
    description: 'Complete daily multivitamin formulated with 24 essential vitamins, zinc, magnesium, and coenzyme Q10 for cellular vitality.',
    rating: 4.9,
    reviews: 1240,
    price: 399,
    originalPrice: 499,
    discount: '20% OFF',
    stock: 112,
    tag: 'Best Seller',
    image: IMAGES.multivitamin,
  },
  {
    name: 'Smart Blood Pressure Monitor AI Sync',
    brand: 'CardioCheck Digital',
    category: 'Diagnostic Devices',
    description: 'Digital upper-arm BP monitor with Bluetooth OLED display, irregular heartbeat detection, and 2-user memory.',
    rating: 4.8,
    reviews: 856,
    price: 1890,
    originalPrice: 2490,
    discount: '24% OFF',
    stock: 45,
    tag: 'Medical Device',
    image: IMAGES.bpMonitor,
  },
  {
    name: 'AccuCheck Glucometer Kit + 50 Test Strips',
    brand: 'AccuCheck Care',
    category: 'Diagnostic Devices',
    description: 'Complete home blood glucose monitoring system with 5-second test results, no coding required, and USB data sync.',
    rating: 4.8,
    reviews: 940,
    price: 1250,
    originalPrice: 1600,
    discount: '22% OFF',
    stock: 55,
    tag: 'Clinical Device',
    image: IMAGES.glucometer,
  },
  {
    name: 'Omega-3 Fish Oil High-Potency 1000mg',
    brand: 'NutriPure Labs',
    category: 'Supplements & Vitamins',
    description: 'Triple-strength EPA/DHA molecularly distilled softgels supporting heart, brain, and joint mobility with zero fishy aftertaste.',
    rating: 4.7,
    reviews: 620,
    price: 649,
    originalPrice: 850,
    discount: '23% OFF',
    stock: 90,
    tag: 'Pure Extract',
    image: IMAGES.omega3,
  },
  {
    name: 'Whey Protein Isolate 1kg - Belgian Chocolate',
    brand: 'ProFit Performance',
    category: 'Fitness & Nutrition',
    description: 'Ultra-filtered 100% whey isolate offering 27g protein and 6g BCAAs per serving with zero added sugar.',
    rating: 4.7,
    reviews: 410,
    price: 2499,
    originalPrice: 3200,
    discount: '22% OFF',
    stock: 35,
    tag: 'Athletic Choice',
    image: IMAGES.protein,
  },
  {
    name: 'Fingertip Pulse Oximeter OLED Display',
    brand: 'VitalSense Health',
    category: 'Diagnostic Devices',
    description: 'Hospital-grade SpO2 blood oxygen saturation and pulse rate monitor with multi-directional display.',
    rating: 4.6,
    reviews: 580,
    price: 699,
    originalPrice: 999,
    discount: '30% OFF',
    stock: 75,
    tag: 'Home Essential',
    image: IMAGES.oximeter,
  },
  {
    name: 'Zinc Sulfate 50mg Immunity Capsules',
    brand: 'NutriPure Labs',
    category: 'Supplements & Vitamins',
    description: 'Chelated zinc formula for immune defense, wound healing, and metabolic enzyme activation.',
    rating: 4.8,
    reviews: 320,
    price: 220,
    originalPrice: 280,
    discount: '21% OFF',
    stock: 140,
    tag: 'Immunity Pack',
    image: IMAGES.multivitamin,
  },
  {
    name: 'Organic Ashwagandha KSM-66 600mg',
    brand: 'Aegis Ayurveda',
    category: 'Herbal & Ayurvedic',
    description: 'Standardized full-spectrum root extract for stress relief, cortisol regulation, and restorative sleep.',
    rating: 4.9,
    reviews: 890,
    price: 499,
    originalPrice: 650,
    discount: '23% OFF',
    stock: 80,
    tag: 'Ayurvedic Gold',
    image: IMAGES.ayurveda,
  },
  {
    name: 'Probiotics 50 Billion CFU Gut Health (60 Caps)',
    brand: 'Optima Nutrition',
    category: 'Digestive Health',
    description: '14 diverse probiotic strains with prebiotic FOS fibers for microbiome balance and digestion support.',
    rating: 4.8,
    reviews: 510,
    price: 799,
    originalPrice: 1050,
    discount: '24% OFF',
    stock: 60,
    tag: 'Gut Health',
    image: IMAGES.multivitamin,
  },
  {
    name: 'Digital Flexible Tip Thermometer (10s Speed)',
    brand: 'VitalSense Health',
    category: 'Diagnostic Devices',
    description: 'Waterproof clinical oral/underarm thermometer with fever alarm and memory recall.',
    rating: 4.7,
    reviews: 670,
    price: 199,
    originalPrice: 299,
    discount: '33% OFF',
    stock: 180,
    tag: 'Home Essential',
    image: IMAGES.thermometer,
  },
  {
    name: 'Calcium Citrate Malate + Vitamin K2-7',
    brand: 'NutriPure Labs',
    category: 'Supplements & Vitamins',
    description: 'High-bioavailability calcium with menaquinone-7 to direct calcium directly into bones.',
    rating: 4.8,
    reviews: 440,
    price: 360,
    originalPrice: 450,
    discount: '20% OFF',
    stock: 95,
    tag: 'Bone Strength',
    image: IMAGES.multivitamin,
  },
  {
    name: 'Coenzyme Q10 (CoQ10) 100mg Bio-Enhanced',
    brand: 'CardioLife Labs',
    category: 'Cardiovascular Health',
    description: 'Potent cellular antioxidant supporting cardiac muscle vitality and statin-depleted CoQ10 restoration.',
    rating: 4.8,
    reviews: 290,
    price: 850,
    originalPrice: 1100,
    discount: '23% OFF',
    stock: 40,
    tag: 'Cardio Vitality',
    image: IMAGES.multivitamin,
  },
  {
    name: 'Melatonin 5mg Fast-Dissolve Sleep Mint',
    brand: 'Optima Nutrition',
    category: 'Sleep & Relaxation',
    description: 'Non-habit forming sublingual melatonin tablets for circadian rhythm restoration and jet lag relief.',
    rating: 4.7,
    reviews: 510,
    price: 299,
    originalPrice: 380,
    discount: '21% OFF',
    stock: 120,
    tag: 'Sleep Aid',
    image: IMAGES.multivitamin,
  },
];

const personalCareData = [
  {
    name: 'Gentle Foaming Salicylic Acid 2% Face Wash 150ml',
    brand: 'ClearDerma Labs',
    category: 'Face Wash & Cleansers',
    description: 'Oil-free acne clearing cleanser with niacinamide to unclog pores and reduce excess sebum without drying skin.',
    price: 299,
    originalPrice: 375,
    discount: '20% OFF',
    stock: 95,
    tag: 'Acne Control',
    image: IMAGES.faceWash,
  },
  {
    name: 'Hydrating Gentle Gel Face Wash with Green Tea 200ml',
    brand: 'DermaRestore Clinical',
    category: 'Face Wash & Cleansers',
    description: 'Soap-free calming face wash enriched with pure green tea extract and hyaluronic acid for daily soothing cleanse.',
    price: 320,
    originalPrice: 400,
    discount: '20% OFF',
    stock: 80,
    tag: 'Dermatologist Approved',
    image: IMAGES.faceWash,
  },
  {
    name: 'DermaRestore Hydrating Ceramides Serum 30ml',
    brand: 'DermaRestore Clinical',
    category: 'Serums & Treatments',
    description: '5 essential ceramides complex with multi-molecular hyaluronic acid for 24h skin barrier restoration.',
    price: 549,
    originalPrice: 699,
    discount: '21% OFF',
    stock: 75,
    tag: 'Dermatologist Verified',
    image: IMAGES.ceramideSerum,
  },
  {
    name: 'BioRepair Anti-Dandruff Active Shampoo 250ml',
    brand: 'BioRepair Hair Sciences',
    category: 'Haircare',
    description: 'Clinically proven 2% Ketoconazole and tea tree oil formulation to eradicate dandruff and soothe itchy scalp.',
    price: 320,
    originalPrice: 399,
    discount: '20% OFF',
    stock: 85,
    tag: 'Haircare Science',
    image: IMAGES.shampoo,
  },
  {
    name: 'UltraShield SPF 50+ PA++++ Mineral Sunscreen 50g',
    brand: 'DermaRestore Clinical',
    category: 'Sun Protection',
    description: 'Invisible zinc non-comedogenic physical sunscreen with blue light filter and zero white cast.',
    price: 480,
    originalPrice: 599,
    discount: '20% OFF',
    stock: 110,
    tag: 'Broad Spectrum',
    image: IMAGES.sunscreen,
  },
  {
    name: 'Rosemary & Redensyl Hair Growth Serum 50ml',
    brand: 'BioRepair Hair Sciences',
    category: 'Haircare',
    description: 'Advanced peptide and rosemary extract serum to stimulate dormant follicles and increase hair density.',
    price: 699,
    originalPrice: 899,
    discount: '22% OFF',
    stock: 60,
    tag: 'Hair Density',
    image: IMAGES.hairOil,
  },
  {
    name: 'Barrier Recovery 10% Niacinamide + Zinc Serum',
    brand: 'DermaRestore Clinical',
    category: 'Serums & Treatments',
    description: 'Pure niacinamide treatment for minimizing enlarged pores, dark spots, and balancing uneven skin tone.',
    price: 449,
    originalPrice: 550,
    discount: '18% OFF',
    stock: 90,
    tag: 'Skin Brightening',
    image: IMAGES.ceramideSerum,
  },
  {
    name: 'Deep Moisture Body Lotion with Urea 10% 400ml',
    brand: 'DermaRestore Clinical',
    category: 'Body Care',
    description: 'Intense dermatologist formula for rough, dry, and bumpy keratosis pilaris skin relief.',
    price: 380,
    originalPrice: 475,
    discount: '20% OFF',
    stock: 80,
    tag: 'Clinical Moisturizer',
    image: IMAGES.bodyLotion,
  },
  {
    name: 'Soothing Centella Asiatica Cica Calming Gel 100g',
    brand: 'ClearDerma Labs',
    category: 'Skincare',
    description: 'Lightweight soothing gel for redness, inflamed skin barrier, and post-sunburn relief.',
    price: 360,
    originalPrice: 450,
    discount: '20% OFF',
    stock: 70,
    tag: 'Cica Therapy',
    image: IMAGES.ceramideSerum,
  },
  {
    name: 'Pure Tea Tree Antiseptic Skin Clarifying Oil 15ml',
    brand: 'Aegis Ayurveda',
    category: 'Organic Care',
    description: '100% pure Australian tea tree essential oil for blemish spot targeting and natural antimicrobial defense.',
    price: 260,
    originalPrice: 325,
    discount: '20% OFF',
    stock: 120,
    tag: '100% Pure',
    image: IMAGES.hairOil,
  },
  {
    name: 'Hydrating Overnight Lip Recovery Butter 15g',
    brand: 'DermaRestore Clinical',
    category: 'Lip Care',
    description: 'Shea butter and peptides intensive treatment for chapped, dry, and peeling lips.',
    price: 199,
    originalPrice: 250,
    discount: '20% OFF',
    stock: 140,
    tag: 'Intense Hydration',
    image: IMAGES.bodyLotion,
  },
  {
    name: 'Onion Black Seed Hair Revitalizing Oil 200ml',
    brand: 'Aegis Ayurveda',
    category: 'Haircare',
    description: 'Cold-pressed botanical oil blend to nourish scalp roots and reduce hair breakage.',
    price: 349,
    originalPrice: 450,
    discount: '22% OFF',
    stock: 100,
    tag: 'Ayurvedic Blend',
    image: IMAGES.hairOil,
  },
  {
    name: 'Alcohol-Free Witch Hazel Balancing Facial Toner 200ml',
    brand: 'ClearDerma Labs',
    category: 'Toners',
    description: 'Botanical pore-refining facial toner with aloe vera to refresh and prep skin without dryness.',
    price: 280,
    originalPrice: 350,
    discount: '20% OFF',
    stock: 85,
    tag: 'Alcohol Free',
    image: IMAGES.faceWash,
  },
  {
    name: 'Clinical Vitamin C 20% + Ferulic Glow Serum 30ml',
    brand: 'DermaRestore Clinical',
    category: 'Serums & Treatments',
    description: 'Potent antioxidant serum protecting against pollution while fading stubborn hyperpigmentation.',
    price: 599,
    originalPrice: 799,
    discount: '25% OFF',
    stock: 65,
    tag: 'Glow Formula',
    image: IMAGES.ceramideSerum,
  },
  {
    name: 'Moisturizing Cream-to-Foam Cleanser 236ml',
    brand: 'DermaRestore Clinical',
    category: 'Face Wash & Cleansers',
    description: 'Gentle amino acid cleanser that cleanses and removes makeup without disrupting skin natural pH.',
    price: 399,
    originalPrice: 499,
    discount: '20% OFF',
    stock: 110,
    tag: 'pH Balanced',
    image: IMAGES.faceWash,
  },
];

const seedDatabase = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI, { dbName: 'pharmacare' });
    console.log('[Seed] Connected to MongoDB Atlas');

    // Clean existing products & demo data
    await Promise.all([
      Medicine.deleteMany({}),
      HealthProduct.deleteMany({}),
      PersonalCareProduct.deleteMany({}),
    ]);
    console.log('[Seed] Cleared existing product collections');

    // Create or update demo user
    const existingUser = await User.findOne({ email: 'owner@pharmacare.ai' });
    let demoUser = existingUser;
    if (!existingUser) {
      demoUser = await User.create({
        name: 'Rahul (Pharmacist Owner)',
        email: 'owner@pharmacare.ai',
        password: 'Password123!',
        role: 'OWNER',
        businessName: 'PharmaCare Central Indiranagar',
        phone: '+91 98765 43210',
        address: '100 Feet Road, Indiranagar, Bangalore 560038',
      });
      console.log('[Seed] Created default demo user: owner@pharmacare.ai / Password123!');
    }

    // Insert Products
    const [insertedMeds, insertedHealth, insertedPersonal] = await Promise.all([
      Medicine.insertMany(medicinesData),
      HealthProduct.insertMany(healthProductsData),
      PersonalCareProduct.insertMany(personalCareData),
    ]);

    console.log(`[Seed Success]: Seeded ${insertedMeds.length} Medicines (including valid, expiring soon, and expired test batches)`);
    console.log(`[Seed Success]: Seeded ${insertedHealth.length} Health Products`);
    console.log(`[Seed Success]: Seeded ${insertedPersonal.length} Personal Care Products`);

    // Create default cart for demo user
    if (demoUser) {
      await Cart.findOneAndUpdate(
        { userId: demoUser._id },
        {
          userId: demoUser._id,
          items: [
            {
              productId: insertedMeds[0]._id,
              productType: 'Medicine',
              name: insertedMeds[0].name,
              price: insertedMeds[0].price,
              qty: 1,
              image: insertedMeds[0].image,
              type: 'Rx',
            },
            {
              productId: insertedHealth[0]._id,
              productType: 'HealthProduct',
              name: insertedHealth[0].name,
              price: insertedHealth[0].price,
              qty: 1,
              image: insertedHealth[0].image,
              type: 'OTC',
            },
          ],
        },
        { upsert: true }
      );
      console.log('[Seed] Seeded default sample cart for demo user');

      // Create an active demo express order
      const existingOrder = await Order.findOne({ userId: demoUser._id });
      if (!existingOrder) {
        await Order.create({
          orderNumber: 'ORD-8942',
          userId: demoUser._id,
          items: [
            {
              productId: insertedMeds[0]._id,
              productType: 'Medicine',
              name: insertedMeds[0].name,
              price: insertedMeds[0].price,
              qty: 1,
              lineTotal: insertedMeds[0].price,
              image: insertedMeds[0].image,
            },
            {
              productId: insertedHealth[0]._id,
              productType: 'HealthProduct',
              name: insertedHealth[0].name,
              price: insertedHealth[0].price,
              qty: 1,
              lineTotal: insertedHealth[0].price,
              image: insertedHealth[0].image,
            },
          ],
          subtotal: 544,
          deliveryFee: 0,
          total: 544,
          shippingAddress: 'Indiranagar 100ft Rd, Bangalore 560038',
          status: 'OUT_FOR_DELIVERY',
          etaMinutes: 18,
          riderName: 'Vikram Singh',
          riderPhone: '+91 98765 43210',
          paymentMethod: 'DEMO_EXPRESS_COD',
          paymentStatus: 'COMPLETED',
        });
        console.log('[Seed] Seeded active live order ORD-8942');
      }
    }

    console.log('--- SEEDING COMPLETED SUCCESSFULLY ---');
    process.exit(0);
  } catch (error) {
    console.error('[Seed Error]:', error);
    process.exit(1);
  }
};

seedDatabase();
