import mongoose from 'mongoose';
import dotenv from 'dotenv';
import bcrypt from 'bcryptjs';
import dns from 'dns';
import { execSync } from 'child_process';

// Fix Windows DNS SRV resolution for MongoDB Atlas if necessary
try {
  if (process.platform === 'win32') {
    const ipconfigOutput = execSync('ipconfig /all', { encoding: 'utf8', timeout: 3000 });
    const detectedIps = Array.from(
      ipconfigOutput.matchAll(/DNS Servers[ .:]+([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)/g),
      (m) => m[1]
    ).filter((ip) => ip !== '127.0.0.1');

    const dnsServers = [...new Set([...detectedIps, '8.8.8.8', '1.1.1.1'])];
    if (dnsServers.length > 0) {
      dns.setServers(dnsServers);
    }
  } else {
    dns.setServers(['8.8.8.8', '1.1.1.1']);
  }
} catch (e) {
  try {
    dns.setServers(['8.8.8.8', '1.1.1.1']);
  } catch (_) {}
}

import User from './models/User.js';
import Medicine from './models/Medicine.js';
import HealthProduct from './models/HealthProduct.js';
import PersonalCareProduct from './models/PersonalCareProduct.js';
import Cart from './models/Cart.js';
import Order from './models/Order.js';

dotenv.config();

/**
 * Generate lightweight, high-performance, crisp SVG product images tied to each exact product
 */
export function generateMedicineSVG({ name, strength = '', form = 'Tablet', category = 'Pain & Fever', color = '#5444ca', bg = '#f0f4ff' }) {
  const encName = encodeURIComponent(name);
  const encStrength = encodeURIComponent(strength || 'Standard');
  const encCategory = encodeURIComponent(category.toUpperCase().slice(0, 16));
  const encForm = encodeURIComponent(form);
  const encColor = encodeURIComponent(color);
  const encBg = encodeURIComponent(bg);

  return `data:image/svg+xml;charset=UTF-8,%3csvg xmlns='http://www.w3.org/2000/svg' width='240' height='240' viewBox='0 0 240 240'%3e%3cdefs%3e%3clinearGradient id='g' x1='0%25' y1='0%25' x2='100%25' y2='100%25'%3e%3cstop offset='0%25' stop-color='${encBg}'/%3e%3cstop offset='100%25' stop-color='%23ffffff'/%3e%3c/linearGradient%3e%3c/defs%3e%3crect width='240' height='240' fill='url(%23g)' rx='24' stroke='${encColor}' stroke-width='2' stroke-opacity='0.25'/%3e%3cg transform='translate(20, 20)'%3e%3crect x='0' y='0' width='90' height='22' rx='6' fill='${encColor}' fill-opacity='0.14'/%3e%3ctext x='45' y='15' font-family='system-ui, -apple-system, sans-serif' font-size='9' font-weight='800' fill='${encColor}' text-anchor='middle' letter-spacing='0.5'%3e${encCategory}%3c/text%3e%3cg transform='translate(60, 42)'%3e%3crect x='0' y='0' width='80' height='54' rx='12' fill='%23ffffff' stroke='${encColor}' stroke-width='2.5'/%3e%3ccircle cx='25' cy='27' r='13' fill='${encColor}' fill-opacity='0.18'/%3e%3ccircle cx='55' cy='27' r='13' fill='${encColor}' fill-opacity='0.18'/%3e%3cline x1='40' y1='8' x2='40' y2='46' stroke='${encColor}' stroke-width='1.5' stroke-dasharray='2,2'/%3e%3c/g%3e%3ctext x='100' y='142' font-family='system-ui, -apple-system, sans-serif' font-size='14' font-weight='800' fill='%230f172a' text-anchor='middle'%3e${encName}%3c/text%3e%3ctext x='100' y='162' font-family='system-ui, -apple-system, sans-serif' font-size='11' font-weight='700' fill='${encColor}' text-anchor='middle'%3e${encStrength} • ${encForm}%3c/text%3e%3crect x='40' y='176' width='120' height='18' rx='9' fill='%2310b981' fill-opacity='0.12'/%3e%3ctext x='100' y='188' font-family='system-ui, -apple-system, sans-serif' font-size='9' font-weight='700' fill='%23059669' text-anchor='middle'%3eVERIFIED PHARMACEUTICAL%3c/text%3e%3c/g%3e%3c/svg%3e`;
}

// Clean "Image unavailable" SVG placeholder
export const IMAGE_UNAVAILABLE = generateMedicineSVG({ name: 'Medicine', strength: 'Standard', form: 'Clinical', category: 'Pharmaceutical', color: '#64748b', bg: '#f8fafc' });

// EXACT 20 MEDICINES WITH AUTHENTIC TABLET/MEDICINE PHOTOGRAPHY & ALIASES
export const EXACT_20_MEDICINES = [
  {
    name: 'Paracetamol 500',
    genericName: 'Paracetamol',
    activeIngredient: 'Paracetamol',
    scientificName: 'N-(4-hydroxyphenyl)acetamide',
    category: 'Pain & Fever',
    strength: '500 mg',
    form: 'Tablet',
    quantity: 100,
    price: 20,
    originalPrice: 25,
    discount: '20% OFF',
    stock: 100,
    brand: 'Calpol 500 / GSK',
    aliases: ['Calpol', 'Calpol 500', 'Crocin 500', 'Paracetamol 500', 'PCM 500'],
    searchKeywords: ['paracetamol', 'calpol', 'crocin', 'fever', 'headache', 'body pain', 'pain relief'],
    manufacturer: 'GSK Pharmaceuticals',
    batchNumber: 'PCM-500-01',
    manufacturingDate: new Date('2026-01-01'),
    expiryDate: new Date('2028-01-01'),
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80'],
    description: 'Effective antipyretic and analgesic for mild-to-moderate fever and body pain.',
    status: 'In Stock',
    uses: ['Fever Reduction', 'Headache', 'Body Pain'],
    precautions: ['Do not exceed 4000 mg in 24 hours', 'Keep 4-6 hours interval between doses'],
    storageInstructions: 'Store below 25°C in a dry place protected from direct sunlight.',
    rxRequired: false,
  },
  {
    name: 'Paracetamol 650',
    genericName: 'Paracetamol',
    activeIngredient: 'Paracetamol',
    scientificName: 'N-(4-hydroxyphenyl)acetamide',
    category: 'Pain & Fever',
    strength: '650 mg',
    form: 'Tablet',
    quantity: 100,
    price: 30,
    originalPrice: 38,
    discount: '21% OFF',
    stock: 100,
    brand: 'Dolo 650 (Micro Labs)',
    aliases: ['Dolo', 'Dolo 650', 'Crocin 650', 'Calpol 650', 'Paracetamol 650', 'PCM 650'],
    searchKeywords: ['dolo', 'dolo 650', 'paracetamol 650', 'crocin 650', 'high fever', 'severe headache', 'body ache', 'pain relief'],
    manufacturer: 'Micro Labs Limited',
    batchNumber: 'PCM-650-02',
    manufacturingDate: new Date('2026-01-01'),
    expiryDate: new Date('2028-01-01'),
    image: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=500&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1585435557343-3b092031a831?w=500&auto=format&fit=crop&q=80'],
    description: 'High-potency antipyretic formulation for severe fever, body aches, and headaches. Widely known as Dolo 650.',
    status: 'In Stock',
    uses: ['Fever Reduction', 'Severe Headache', 'Post-vaccination Fever', 'Body Aches'],
    precautions: ['Do not exceed recommended dose', 'Avoid alcohol consumption'],
    storageInstructions: 'Store below 25°C in a dry place.',
    rxRequired: false,
  },
  {
    name: 'Cetirizine 10',
    genericName: 'Cetirizine',
    activeIngredient: 'Cetirizine',
    scientificName: '2-[2-[4-[(4-chlorophenyl)-phenylmethyl]piperazin-1-yl]ethoxy]acetic acid',
    category: 'Allergy',
    strength: '10 mg',
    form: 'Tablet',
    quantity: 50,
    price: 25,
    originalPrice: 32,
    discount: '22% OFF',
    stock: 50,
    brand: 'AllerShield / Zyrtec',
    aliases: ['Cetirizine', 'Zyrtec', 'Cetzine', 'AllerShield', 'Cetirizine 10'],
    searchKeywords: ['cetirizine', 'allergy', 'sneezing', 'runny nose', 'cold', 'itching'],
    manufacturer: 'PharmaCare Laboratories',
    batchNumber: 'CTZ-10-03',
    manufacturingDate: new Date('2026-01-01'),
    expiryDate: new Date('2028-01-01'),
    image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=500&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=500&auto=format&fit=crop&q=80'],
    description: 'Second-generation antihistamine providing 24-hour relief from seasonal allergies, sneezing, and runny nose.',
    status: 'In Stock',
    uses: ['Allergic Rhinitis', 'Sneezing', 'Runny Nose', 'Skin Itching'],
    precautions: ['May cause mild drowsiness in some individuals'],
    storageInstructions: 'Store in a cool, dry place away from moisture.',
    rxRequired: false,
  },
  {
    name: 'Pantoprazole 40',
    genericName: 'Pantoprazole',
    activeIngredient: 'Pantoprazole',
    scientificName: '(RS)-6-(difluoromethoxy)-2-[(3,4-dimethoxypyridin-2-yl)methylsulfinyl]-1H-benzo[d]imidazole',
    category: 'Gastric/Acidity',
    strength: '40 mg',
    form: 'Tablet',
    quantity: 50,
    price: 45,
    originalPrice: 58,
    discount: '22% OFF',
    stock: 50,
    brand: 'Pan 40 / GastroFix',
    aliases: ['Pan 40', 'Pantocid', 'Pantoprazole', 'Pan', 'GastroFix'],
    searchKeywords: ['pan 40', 'pantoprazole', 'acidity', 'gas', 'gerd', 'heartburn', 'gastric'],
    manufacturer: 'Alkem Laboratories',
    batchNumber: 'PAN-40-04',
    manufacturingDate: new Date('2026-01-01'),
    expiryDate: new Date('2028-01-01'),
    image: 'https://images.unsplash.com/photo-1550572017-ed24c44933ff?w=500&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1550572017-ed24c44933ff?w=500&auto=format&fit=crop&q=80'],
    description: 'Proton-pump inhibitor for acid reflux, heartburn, and peptic ulcer relief.',
    status: 'In Stock',
    uses: ['Gastroesophageal Reflux Disease (GERD)', 'Heartburn', 'Stomach Acidity'],
    precautions: ['Take 30-60 minutes before breakfast for optimal efficacy'],
    storageInstructions: 'Store below 25°C protected from light.',
    rxRequired: false,
  },
  {
    name: 'Omeprazole 20',
    genericName: 'Omeprazole',
    activeIngredient: 'Omeprazole',
    scientificName: '(RS)-5-methoxy-2-[(4-methoxy-3,5-dimethylpyridin-2-yl)methylsulfinyl]-1H-benzimidazole',
    category: 'Gastric/Acidity',
    strength: '20 mg',
    form: 'Capsule',
    quantity: 50,
    price: 35,
    originalPrice: 45,
    discount: '22% OFF',
    stock: 50,
    brand: 'Omez 20 / Dr. Reddy',
    aliases: ['Omez', 'Omez 20', 'Omeprazole', 'OmezCare'],
    searchKeywords: ['omez', 'omeprazole', 'acidity', 'stomach ache', 'acid reflux', 'gastric'],
    manufacturer: 'Dr. Reddy Laboratories',
    batchNumber: 'OMP-20-05',
    manufacturingDate: new Date('2026-01-01'),
    expiryDate: new Date('2028-01-01'),
    image: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?w=500&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1628771065518-0d82f1938462?w=500&auto=format&fit=crop&q=80'],
    description: 'Delayed-release capsule that reduces stomach acid for acidity and gastric comfort.',
    status: 'In Stock',
    uses: ['Acid Reflux', 'Dyspepsia', 'Gastric Ulcer Prevention'],
    precautions: ['Swallow whole; do not crush or chew capsule'],
    storageInstructions: 'Store in airtight container below 25°C.',
    rxRequired: false,
  },
  {
    name: 'ORS Sachet',
    genericName: 'Oral Rehydration Salts',
    activeIngredient: 'Oral Rehydration Salts',
    scientificName: 'Sodium Chloride, Potassium Chloride, Sodium Citrate, Anhydrous Dextrose',
    category: 'Rehydration',
    strength: '21.8 g',
    form: 'Sachet',
    quantity: 100,
    price: 20,
    originalPrice: 24,
    discount: '16% OFF',
    stock: 100,
    brand: 'Electral / WHO Formula',
    aliases: ['Electral', 'ORS', 'Oral Rehydration Salts', 'HydroRestore'],
    searchKeywords: ['ors', 'electral', 'dehydration', 'diarrhea', 'electrolyte', 'energy powder'],
    manufacturer: 'FDC Limited',
    batchNumber: 'ORS-100-06',
    manufacturingDate: new Date('2026-01-01'),
    expiryDate: new Date('2028-01-01'),
    image: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=500&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=500&auto=format&fit=crop&q=80'],
    description: 'WHO-formulated electrolyte powder for rapid restoration of fluids and essential salts during dehydration.',
    status: 'In Stock',
    uses: ['Dehydration', 'Diarrhea Recovery', 'Electrolyte Balance', 'Heat Fatigue'],
    precautions: ['Dissolve in exact recommended quantity of clean drinking water'],
    storageInstructions: 'Store in a cool dry place.',
    rxRequired: false,
  },
  {
    name: 'Azithromycin 500',
    genericName: 'Azithromycin',
    activeIngredient: 'Azithromycin',
    scientificName: 'Azithromycin dihydrate',
    category: 'Antibiotic',
    strength: '500 mg',
    form: 'Tablet',
    quantity: 30,
    price: 120,
    originalPrice: 150,
    discount: '20% OFF',
    stock: 30,
    brand: 'Azithral 500 / Alembic',
    aliases: ['Azithral', 'Azithral 500', 'Azithromycin', 'AziShield'],
    searchKeywords: ['azithromycin', 'azithral', 'antibiotic', 'throat infection', 'chest infection', 'bacterial'],
    manufacturer: 'Alembic Pharmaceuticals',
    batchNumber: 'AZM-500-07',
    manufacturingDate: new Date('2026-01-01'),
    expiryDate: new Date('2028-01-01'),
    image: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500&auto=format&fit=crop&q=80'],
    description: 'Broad-spectrum macrolide antibiotic for respiratory tract and soft tissue bacterial infections.',
    status: 'In Stock',
    uses: ['Respiratory Infections', 'Bacterial Pharyngitis', 'Sinusitis'],
    precautions: ['Complete full course prescribed by physician'],
    storageInstructions: 'Store below 25°C.',
    rxRequired: true,
  },
  {
    name: 'Amoxicillin 500',
    genericName: 'Amoxicillin',
    activeIngredient: 'Amoxicillin',
    scientificName: 'Amoxicillin Trihydrate',
    category: 'Antibiotic',
    strength: '500 mg',
    form: 'Capsule',
    quantity: 30,
    price: 90,
    originalPrice: 115,
    discount: '21% OFF',
    stock: 30,
    brand: 'Mox 500 / Sun Pharma',
    aliases: ['Mox', 'Mox 500', 'Amoxicillin', 'Amoxil', 'AmoxiCure'],
    searchKeywords: ['amoxicillin', 'mox 500', 'antibiotic', 'ear infection', 'throat infection', 'chest infection'],
    manufacturer: 'Sun Pharma Laboratories',
    batchNumber: 'AMX-500-08',
    manufacturingDate: new Date('2026-01-01'),
    expiryDate: new Date('2028-01-01'),
    image: 'https://images.unsplash.com/photo-1577401239170-897942555fb3?w=500&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1577401239170-897942555fb3?w=500&auto=format&fit=crop&q=80'],
    description: 'Broad-spectrum penicillin antibiotic effective against ear, throat, and chest bacterial infections.',
    status: 'In Stock',
    uses: ['Bacterial Infections', 'Strep Throat', 'Ear Infection', 'Chest Infection'],
    precautions: ['Do not use if allergic to penicillin or beta-lactams'],
    storageInstructions: 'Store below 25°C in a dry place.',
    rxRequired: true,
  },
  {
    name: 'Ibuprofen 400',
    genericName: 'Ibuprofen',
    activeIngredient: 'Ibuprofen',
    scientificName: '(RS)-2-(4-(2-methylpropyl)phenyl)propanoic acid',
    category: 'Pain & Inflammation',
    strength: '400 mg',
    form: 'Tablet',
    quantity: 50,
    price: 40,
    originalPrice: 50,
    discount: '20% OFF',
    stock: 50,
    brand: 'Brufen 400 / Abbott',
    aliases: ['Brufen', 'Brufen 400', 'Ibuprofen', 'BrufenCare'],
    searchKeywords: ['ibuprofen', 'brufen', 'joint pain', 'muscle pain', 'dental pain', 'inflammation', 'swelling'],
    manufacturer: 'Abbott Healthcare',
    batchNumber: 'IBU-400-09',
    manufacturingDate: new Date('2026-01-01'),
    expiryDate: new Date('2028-01-01'),
    image: 'https://images.unsplash.com/photo-1550572017-4fcdbb590e5b?w=500&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1550572017-4fcdbb590e5b?w=500&auto=format&fit=crop&q=80'],
    description: 'Non-steroidal anti-inflammatory drug (NSAID) for muscle pain, dental ache, and swelling.',
    status: 'In Stock',
    uses: ['Joint Pain', 'Muscle Pain', 'Dental Ache', 'Inflammation'],
    precautions: ['Take after food to avoid gastric irritation'],
    storageInstructions: 'Store below 25°C.',
    rxRequired: false,
  },
  {
    name: 'Diclofenac 50',
    genericName: 'Diclofenac',
    activeIngredient: 'Diclofenac',
    scientificName: '2-[2-(2,6-dichloroanilino)phenyl]acetic acid',
    category: 'Pain & Inflammation',
    strength: '50 mg',
    form: 'Tablet',
    quantity: 50,
    price: 35,
    originalPrice: 45,
    discount: '22% OFF',
    stock: 50,
    brand: 'Voveran 50 / Novartis',
    aliases: ['Voveran', 'Voveran 50', 'Diclofenac', 'DicloFast'],
    searchKeywords: ['diclofenac', 'voveran', 'severe pain', 'arthritis', 'back pain', 'joint pain'],
    manufacturer: 'Novartis India',
    batchNumber: 'DIC-50-10',
    manufacturingDate: new Date('2026-01-01'),
    expiryDate: new Date('2028-01-01'),
    image: 'https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?w=500&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?w=500&auto=format&fit=crop&q=80'],
    description: 'Potent NSAID formulation for severe joint inflammation, back pain, and arthritis.',
    status: 'In Stock',
    uses: ['Severe Body Pain', 'Rheumatoid Arthritis', 'Osteoarthritis', 'Back Pain'],
    precautions: ['Use shortest effective duration; take with food'],
    storageInstructions: 'Store in a dry place protected from light.',
    rxRequired: true,
  },
  {
    name: 'Levocetirizine 5',
    genericName: 'Levocetirizine',
    activeIngredient: 'Levocetirizine',
    scientificName: '2-[2-[4-[(R)-(4-chlorophenyl)-phenylmethyl]piperazin-1-yl]ethoxy]acetic acid',
    category: 'Allergy',
    strength: '5 mg',
    form: 'Tablet',
    quantity: 50,
    price: 45,
    originalPrice: 58,
    discount: '22% OFF',
    stock: 50,
    brand: 'Levocet / Cipla',
    aliases: ['Levocet', 'Levocet 5', 'Levocetirizine', 'L-Cetridoc'],
    searchKeywords: ['levocetirizine', 'levocet', 'allergy', 'cold', 'sneezing', 'hives', 'skin allergy'],
    manufacturer: 'Cipla Limited',
    batchNumber: 'LVC-5-11',
    manufacturingDate: new Date('2026-01-01'),
    expiryDate: new Date('2028-01-01'),
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80'],
    description: 'High-affinity active enantiomer of cetirizine for rapid relief from allergic symptoms.',
    status: 'In Stock',
    uses: ['Chronic Urticaria', 'Allergic Sneezing', 'Watery Eyes', 'Skin Hives'],
    precautions: ['Avoid driving or operating heavy machinery if feeling drowsy'],
    storageInstructions: 'Store below 30°C.',
    rxRequired: false,
  },
  {
    name: 'Metformin 500',
    genericName: 'Metformin',
    activeIngredient: 'Metformin',
    scientificName: '1,1-dimethylbiguanide hydrochloride',
    category: 'Diabetes',
    strength: '500 mg',
    form: 'Tablet',
    quantity: 100,
    price: 50,
    originalPrice: 65,
    discount: '23% OFF',
    stock: 100,
    brand: 'Glycomet 500 / USV',
    aliases: ['Glycomet', 'Glycomet 500', 'Metformin', 'GlucoReg'],
    searchKeywords: ['metformin', 'glycomet', 'diabetes', 'blood sugar', 'sugar control'],
    manufacturer: 'USV Private Limited',
    batchNumber: 'MET-500-12',
    manufacturingDate: new Date('2026-01-01'),
    expiryDate: new Date('2028-01-01'),
    image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=500&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=500&auto=format&fit=crop&q=80'],
    description: 'First-line oral biguanide medication for glycemic control in Type 2 Diabetes.',
    status: 'In Stock',
    uses: ['Type 2 Diabetes Mellitus', 'Glycemic Control', 'Insulin Sensitivity Support'],
    precautions: ['Take with or immediately after meals to reduce gastrointestinal discomfort'],
    storageInstructions: 'Store below 25°C in a moisture-free area.',
    rxRequired: true,
  },
  {
    name: 'Amlodipine 5',
    genericName: 'Amlodipine',
    activeIngredient: 'Amlodipine',
    scientificName: '(RS)-3-ethyl 5-methyl 2-[(2-aminoethoxy)methyl]-4-(2-chlorophenyl)-6-methyl-1,4-dihydropyridine-3,5-dicarboxylate',
    category: 'Blood Pressure',
    strength: '5 mg',
    form: 'Tablet',
    quantity: 100,
    price: 35,
    originalPrice: 45,
    discount: '22% OFF',
    stock: 100,
    brand: 'Amlong 5 / Micro Labs',
    aliases: ['Amlong', 'Amlong 5', 'Amlodipine', 'CardioPress'],
    searchKeywords: ['amlodipine', 'amlong', 'blood pressure', 'bp', 'hypertension', 'heart'],
    manufacturer: 'Micro Labs Limited',
    batchNumber: 'AML-5-13',
    manufacturingDate: new Date('2026-01-01'),
    expiryDate: new Date('2028-01-01'),
    image: 'https://images.unsplash.com/photo-1550572017-ed24c44933ff?w=500&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1550572017-ed24c44933ff?w=500&auto=format&fit=crop&q=80'],
    description: 'Long-acting calcium channel blocker used in the management of hypertension and angina.',
    status: 'In Stock',
    uses: ['Hypertension (High Blood Pressure)', 'Chronic Stable Angina'],
    precautions: ['Regular blood pressure monitoring recommended; do not stop abruptly'],
    storageInstructions: 'Store below 25°C.',
    rxRequired: true,
  },
  {
    name: 'Losartan 50',
    genericName: 'Losartan',
    activeIngredient: 'Losartan',
    scientificName: '[2-butyl-5-chloro-3-[[4-[2-(2H-tetrazol-5-yl)phenyl]phenyl]methyl]imidazol-4-yl]methanol',
    category: 'Blood Pressure',
    strength: '50 mg',
    form: 'Tablet',
    quantity: 50,
    price: 60,
    originalPrice: 75,
    discount: '20% OFF',
    stock: 50,
    brand: 'Losar 50 / Unichem',
    aliases: ['Losar', 'Losar 50', 'Losartan', 'VasoProtect'],
    searchKeywords: ['losartan', 'losar', 'blood pressure', 'bp', 'hypertension', 'kidney protection'],
    manufacturer: 'Unichem Laboratories',
    batchNumber: 'LOS-50-14',
    manufacturingDate: new Date('2026-01-01'),
    expiryDate: new Date('2028-01-01'),
    image: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=500&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1585435557343-3b092031a831?w=500&auto=format&fit=crop&q=80'],
    description: 'Angiotensin II receptor antagonist (ARB) for hypertension and renal protection.',
    status: 'In Stock',
    uses: ['Hypertension', 'Diabetic Nephropathy Support', 'Cardiovascular Risk Reduction'],
    precautions: ['Contraindicated during pregnancy; check serum potassium levels periodically'],
    storageInstructions: 'Store in airtight container below 25°C.',
    rxRequired: true,
  },
  {
    name: 'Atorvastatin 10',
    genericName: 'Atorvastatin',
    activeIngredient: 'Atorvastatin',
    scientificName: '(3R,5R)-7-[2-(4-fluorophenyl)-3-phenyl-4-(phenylcarbamoyl)-5-propan-2-ylpyrrol-1-yl]-3,5-dihydroxyheptanoic acid',
    category: 'Cholesterol',
    strength: '10 mg',
    form: 'Tablet',
    quantity: 50,
    price: 55,
    originalPrice: 70,
    discount: '21% OFF',
    stock: 50,
    brand: 'Atorva 10 / Zydus',
    aliases: ['Atorva', 'Atorva 10', 'Atorvastatin', 'LipidNorm'],
    searchKeywords: ['atorvastatin', 'atorva', 'cholesterol', 'triglycerides', 'lipid', 'heart health'],
    manufacturer: 'Zydus Lifesciences',
    batchNumber: 'ATV-10-15',
    manufacturingDate: new Date('2026-01-01'),
    expiryDate: new Date('2028-01-01'),
    image: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500&auto=format&fit=crop&q=80'],
    description: 'HMG-CoA reductase inhibitor (statin) for lowering LDL cholesterol and triglycerides.',
    status: 'In Stock',
    uses: ['Hypercholesterolemia', 'Dyslipidemia', 'Prevention of Cardiovascular Events'],
    precautions: ['Take preferably at evening bedtime; avoid excessive grapefruit consumption'],
    storageInstructions: 'Store below 25°C.',
    rxRequired: true,
  },
  {
    name: 'Ondansetron 4',
    genericName: 'Ondansetron',
    activeIngredient: 'Ondansetron',
    scientificName: '(RS)-9-methyl-3-[(2-methyl-1H-imidazol-1-yl)methyl]-2,3-dihydro-1H-carbazol-4-one',
    category: 'Anti-nausea',
    strength: '4 mg',
    form: 'Tablet',
    quantity: 30,
    price: 40,
    originalPrice: 50,
    discount: '20% OFF',
    stock: 30,
    brand: 'Emeset 4 / Cipla',
    aliases: ['Emeset', 'Emeset 4', 'Ondansetron', 'VomiSoothe'],
    searchKeywords: ['ondansetron', 'emeset', 'vomiting', 'nausea', 'motion sickness', 'stomach upset'],
    manufacturer: 'Cipla Limited',
    batchNumber: 'OND-4-16',
    manufacturingDate: new Date('2026-01-01'),
    expiryDate: new Date('2028-01-01'),
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80'],
    description: 'Serotonin 5-HT3 receptor antagonist for nausea and vomiting control.',
    status: 'In Stock',
    uses: ['Nausea and Vomiting Prevention', 'Post-operative Emesis', 'Gastroenteritis Emesis'],
    precautions: ['Take 30 minutes before food or as directed by physician'],
    storageInstructions: 'Store protected from light and moisture.',
    rxRequired: true,
  },
  {
    name: 'Dextromethorphan Syrup',
    genericName: 'Dextromethorphan',
    activeIngredient: 'Dextromethorphan Hydrobromide',
    scientificName: '(4bS,8aR,9S)-3-methoxy-11-methyl-6,7,8,8a,9,10-hexahydro-5H-9,4b-(epiminoethano)phenanthrene',
    category: 'Cough',
    strength: '10 mg/5ml',
    form: 'Syrup',
    quantity: 20,
    price: 85,
    originalPrice: 110,
    discount: '22% OFF',
    stock: 20,
    brand: 'TussinClear / Benadryl DR',
    aliases: ['TussinClear', 'Dextromethorphan', 'Cough Syrup', 'Benadryl DR'],
    searchKeywords: ['dextromethorphan', 'cough syrup', 'dry cough', 'throat irritation', 'cough relief'],
    manufacturer: 'Johnson & Johnson Healthcare',
    batchNumber: 'DXM-100-17',
    manufacturingDate: new Date('2026-01-01'),
    expiryDate: new Date('2028-01-01'),
    image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80'],
    description: 'Centrally-acting antitussive cough suppressant for dry, non-productive cough relief.',
    status: 'In Stock',
    uses: ['Dry Cough', 'Throat Tickle Suppression', 'Irritant-Induced Cough'],
    precautions: ['Not recommended for persistent productive wet cough with excess mucus'],
    storageInstructions: 'Store below 25°C; do not freeze.',
    rxRequired: false,
  },
  {
    name: 'Antacid Suspension',
    genericName: 'Aluminium + Magnesium Hydroxide',
    activeIngredient: 'Aluminium Hydroxide, Magnesium Hydroxide, Simethicone',
    scientificName: 'Aluminium Hydroxide + Magnesium Hydroxide + Dimethicone',
    category: 'Acidity',
    strength: '200 ml',
    form: 'Suspension',
    quantity: 20,
    price: 90,
    originalPrice: 115,
    discount: '21% OFF',
    stock: 20,
    brand: 'Gelusil MPS / Digene',
    aliases: ['Gelusil', 'Digene', 'Antacid Suspension', 'AcidiRelief Gel'],
    searchKeywords: ['gelusil', 'digene', 'antacid', 'acidity', 'gas relief', 'heartburn', 'stomach burning'],
    manufacturer: 'Pfizer India',
    batchNumber: 'ANT-200-18',
    manufacturingDate: new Date('2026-01-01'),
    expiryDate: new Date('2028-01-01'),
    image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80'],
    description: 'Fast-acting soothing liquid antacid neutralizing excess stomach acid and alleviating bloating.',
    status: 'In Stock',
    uses: ['Heartburn', 'Acid Indigestion', 'Flatulence & Bloating', 'Sour Stomach'],
    precautions: ['Shake well before use; take after meals and at bedtime'],
    storageInstructions: 'Store below 25°C in tightly closed bottle.',
    rxRequired: false,
  },
  {
    name: 'Vitamin B-Complex',
    genericName: 'B Vitamins',
    activeIngredient: 'Thiamine, Riboflavin, Niacinamide, Pyridoxine, Cyanocobalamin',
    scientificName: 'Multivitamin B-Complex with Zinc & Folic Acid',
    category: 'Supplement',
    strength: 'High Potency',
    form: 'Tablet',
    quantity: 100,
    price: 70,
    originalPrice: 90,
    discount: '22% OFF',
    stock: 100,
    brand: 'Becosules / Pfizer',
    aliases: ['Becosules', 'B-Complex', 'Vitamin B', 'NutriB Boost'],
    searchKeywords: ['becosules', 'vitamin b', 'b complex', 'mouth ulcers', 'energy', 'weakness', 'supplement'],
    manufacturer: 'Pfizer Healthcare',
    batchNumber: 'VBC-100-19',
    manufacturingDate: new Date('2026-01-01'),
    expiryDate: new Date('2028-01-01'),
    image: 'https://images.unsplash.com/photo-1563213126-a4273aed2016?w=500&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1563213126-a4273aed2016?w=500&auto=format&fit=crop&q=80'],
    description: 'Essential Vitamin B complex with Zinc and Vitamin C for cellular energy metabolism and immune vitality.',
    status: 'In Stock',
    uses: ['Nutritional Deficiency', 'Mouth Ulcer Relief', 'Immune Support', 'Energy Metabolism'],
    precautions: ['Take daily with plenty of water after food'],
    storageInstructions: 'Store below 25°C away from moisture.',
    rxRequired: false,
  },
  {
    name: 'Calcium + Vitamin D3',
    genericName: 'Calcium + Vitamin D3',
    activeIngredient: 'Calcium Carbonate, Cholecalciferol (Vitamin D3)',
    scientificName: 'Calcium Carbonate 500mg + Vitamin D3 250 IU',
    category: 'Supplement',
    strength: '500 mg + 250 IU',
    form: 'Tablet',
    quantity: 100,
    price: 100,
    originalPrice: 130,
    discount: '23% OFF',
    stock: 100,
    brand: 'Shelcal 500 / Torrent',
    aliases: ['Shelcal', 'Shelcal 500', 'Calcium D3', 'CalciBone'],
    searchKeywords: ['shelcal', 'calcium', 'vitamin d3', 'bone strength', 'joint health', 'supplement'],
    manufacturer: 'Torrent Pharmaceuticals',
    batchNumber: 'CAL-500-20',
    manufacturingDate: new Date('2026-01-01'),
    expiryDate: new Date('2028-01-01'),
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80'],
    description: 'High-absorption calcium with Vitamin D3 for optimal bone mineral density and joint strength.',
    status: 'In Stock',
    uses: ['Osteoporosis Prevention', 'Bone Density Support', 'Calcium Deficiency', 'Joint Strength'],
    precautions: ['Do not exceed recommended daily allowance; drink adequate water'],
    storageInstructions: 'Store in a cool dry place away from sunlight.',
    rxRequired: false,
  },
];

export async function seedDatabase() {
  const uri = process.env.MONGODB_URI;
  if (!uri) {
    console.warn('[Seed] MONGODB_URI not found. Skipping seeding.');
    return;
  }

  try {
    if (mongoose.connection.readyState !== 1) {
      await mongoose.connect(uri, {
        serverSelectionTimeoutMS: 5000,
        connectTimeoutMS: 5000,
      });
      console.log('[Seed] Connected to MongoDB Atlas');
    }

    // 1. Seed or Upsert Default Users (Demo User and Owner)
    const salt = await bcrypt.genSalt(10);
    const passwordHash = await bcrypt.hash('password123', salt);

    const defaultUsers = [
      {
        name: 'Demo User',
        email: 'demo@pharmacare.ai',
        password: passwordHash,
        role: 'USER',
        businessName: 'PharmaCare Central',
        address: 'Indiranagar, Bangalore 560038',
      },
      {
        name: 'Owner Admin',
        email: 'owner@pharmacare.ai',
        password: passwordHash,
        role: 'OWNER',
        businessName: 'PharmaCare HQ',
        address: 'MG Road, Bangalore 560001',
      },
    ];

    for (const u of defaultUsers) {
      const existing = await User.findOne({ email: u.email });
      if (!existing) {
        await User.create(u);
        console.log(`[Seed] Created default user: ${u.email}`);
      }
    }

    // 2. Seed or Update Exactly the 20 Medicines with compound unique key
    for (const med of EXACT_20_MEDICINES) {
      await Medicine.findOneAndUpdate(
        { name: med.name, strength: med.strength, form: med.form },
        { $set: med },
        { upsert: true, new: true, setDefaultsOnInsert: true }
      );
    }
    console.log(`[Seed] Verified and synced exact 20 medicines in MongoDB.`);

    // Clean up any outdated test records that don't match the 20 medicines
    const validNames = EXACT_20_MEDICINES.map((m) => m.name);
    const deletedLegacy = await Medicine.deleteMany({ name: { $nin: validNames } });
    if (deletedLegacy.deletedCount > 0) {
      console.log(`[Seed] Cleaned up ${deletedLegacy.deletedCount} legacy non-matching records.`);
    }

    console.log('[Seed] Database seeding completed successfully.');
  } catch (err) {
    console.error('[Seed] Database seeding error:', err.message);
  }
}

// Run directly if executed as script
if (process.argv[1]?.endsWith('seed.js')) {
  seedDatabase().then(() => {
    process.exit(0);
  });
}

export default seedDatabase;
